/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUPersonalRequestsEditorItemManager : HFItemManager {
    HMHome * _homeForUser;
    HUPersonalRequestsDevicesItemModule * _prDevicesModule;
    HFStaticItemProvider * _staticItemProvider;
}

@property (nonatomic, readonly) HMAssistantAccessControl *accessControl;
@property (nonatomic, readonly) HMHome *homeForUser;
@property (nonatomic) unsigned long long personalRequestsAuthenticationRequirement;
@property (nonatomic, retain) HUPersonalRequestsDevicesItemModule *prDevicesModule;
@property (nonatomic, retain) HFUserItem *sourceItem;
@property (nonatomic, readonly) HFStaticItemProvider *staticItemProvider;
@property (nonatomic, readonly) HMUser *user;

- (void).cxx_destruct;
- (bool)_arePersonalRequestsEnabled;
- (id)_buildItemProvidersForHome:(id)arg1;
- (id)_buildSectionsWithDisplayedItems:(id)arg1;
- (id)_commitUpdateToAccessControl:(id)arg1;
- (void)_registerForExternalUpdates;
- (void)_unregisterForExternalUpdates;
- (id)accessControl;
- (id)homeForUser;
- (id)initWithDelegate:(id)arg1 sourceItem:(id)arg2;
- (id)initWithDelegate:(id)arg1 userItem:(id)arg2;
- (unsigned long long)personalRequestsAuthenticationRequirement;
- (id)prDevicesModule;
- (void)setPersonalRequestsAuthenticationRequirement:(unsigned long long)arg1;
- (void)setPrDevicesModule:(id)arg1;
- (id)staticItemProvider;
- (id)user;

@end
