/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface SFPasswordPickerServiceViewController : SFPasswordServiceViewController <SFPasswordPickerServiceViewControllerProtocol, _SFAuthenticationClient, _SFAuthenticationContextDelegate> {
    _SFAuthenticationContext * _context;
    bool  _hasAuthenticationForOtherPasswords;
    WBUPasswordPickerViewController * _passwordPickerViewController;
    bool  _presentInPopover;
    NSURL * _webViewURL;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_exportedInterface;

- (void).cxx_destruct;
- (void)_authenticateToViewOtherPasswordsWithCompletion:(id /* block */)arg1;
- (id)_context;
- (void)_dismiss;
- (void)_gatherAndShowPasswordsWithCompletion:(id /* block */)arg1;
- (id)_hintStringsForAppID:(id)arg1 appName:(id)arg2 credentials:(id)arg3 webViewURL:(id)arg4;
- (void)authenticateToPresentInPopover:(bool)arg1 completion:(id /* block */)arg2;
- (id)authenticationCustomUIProgressObserverForContext:(id)arg1;
- (bool)authenticationEnabledForContext:(id)arg1;
- (id)authenticationMessageForContext:(id)arg1;
- (bool)contextRequiresSessionBasedAuthentication:(id)arg1;
- (bool)contextShouldAllowMultipleBiometricFailures:(id)arg1;
- (bool)contextShouldAllowPasscodeFallback:(id)arg1;
- (void)setWebViewURL:(id)arg1;

@end
