/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface SFPasswordPickerRemoteViewController : SFPasswordRemoteViewController

+ (id)passwordServiceViewControllerName;
+ (id)serviceViewControllerInterface;

@end
