/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BarcodeSupport.framework/BarcodeSupport
 */

@interface BCSNotificationService : NSObject <BCSNotificationServiceProtocol>

- (void)_cancelNotifications;
- (void)cancelNotifications;
- (void)notifyParsedBarcodeWithData:(id)arg1 codePayload:(id)arg2 reply:(id /* block */)arg3;

@end
