/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKAAUIDeviceToDeviceEncryptionHelper : NSObject

+ (Class)ck_AAUIDeviceToDeviceEncryptionHelperClass;
+ (id)ck_deviceToDeviceEncryptionHelperWithPresentingViewController:(id)arg1;

@end
