/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKACAccountStore : NSObject

+ (Class)ck_ACAccountStoreClass;
+ (id)ck_accountStore;

@end
