/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKAKAppleIDAuthenticationContext : NSObject

+ (Class)ck_AKAppleIDAuthenticationContextClass;
+ (id)ck_AKSecurityUpgradeContextMessages;
+ (id)ck_authenticationContext;
+ (id)ck_messagesAuthenticationContext;

@end
