/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKAKAccountManager : NSObject

+ (Class)ck_AKAccountManagerClass;
+ (id)ck_sharedInstance;

@end
