/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSCHChartTypePieFamily : TSCH2DChartType

- (id)animationDeliveryStylesForFilter:(id)arg1;
- (bool)explosionAffectsChartBodyBounds;
- (bool)includeValueLabelPositionOff;
- (id)init;
- (bool)layoutFrameShouldEncloseInfoGeometry;
- (struct CGSize { double x1; double x2; })mungeBodySize:(struct CGSize { double x1; double x2; })arg1;
- (Class)repClass;
- (bool)shouldChangeExplosionWithPreviousChartType:(id)arg1 seriesList:(id)arg2;

@end
