/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSDBezierHitTesterPointInfo : NSObject {
    bool  _isFilledPoint;
    unsigned long long  _pathId;
    double  _percentAlongPath;
    struct CGPoint { 
        double x; 
        double y; 
    }  _precisePoint;
}

@property (nonatomic) bool isFilledPoint;
@property (nonatomic) unsigned long long pathId;
@property (nonatomic) double percentAlongPath;
@property (nonatomic) struct CGPoint { double x1; double x2; } precisePoint;

- (id)description;
- (bool)isFilledPoint;
- (unsigned long long)pathId;
- (double)percentAlongPath;
- (struct CGPoint { double x1; double x2; })precisePoint;
- (void)setIsFilledPoint:(bool)arg1;
- (void)setPathId:(unsigned long long)arg1;
- (void)setPercentAlongPath:(double)arg1;
- (void)setPrecisePoint:(struct CGPoint { double x1; double x2; })arg1;

@end
