/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSDBezierHitTesterHitInfo : NSObject {
    double  _distanceBetweenPoints;
    TSUBezierPath * _hitPath;
    struct CGPoint { 
        double x; 
        double y; 
    }  _hitPoint;
    struct CGPoint { 
        double x; 
        double y; 
    }  _testPoint;
}

@property (nonatomic, readonly) double distanceBetweenPoints;
@property (nonatomic, readonly) TSUBezierPath *hitPath;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } hitPoint;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } testPoint;

- (void).cxx_destruct;
- (id)description;
- (double)distanceBetweenPoints;
- (id)hitPath;
- (struct CGPoint { double x1; double x2; })hitPoint;
- (id)initWithTestPoint:(struct CGPoint { double x1; double x2; })arg1 hitPoint:(struct CGPoint { double x1; double x2; })arg2 hitPath:(id)arg3;
- (struct CGPoint { double x1; double x2; })testPoint;

@end
