/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSDBezierHitTester : NSObject {
    TSUPointerKeyDictionary * _allFilledPointInfosForPathDictionary;
    TSUPointerKeyDictionary * _allNonFilledPointInfosForPathDictionary;
    NSMutableArray * _allPathArray;
    unsigned long long  _bucketSize;
    NSMutableDictionary * _pointInfoGridDictionary;
}

- (void).cxx_destruct;
- (void)addPath:(id)arg1 filled:(bool)arg2;
- (id)allHitsAlongPath:(id)arg1 withSearchThreshold:(double)arg2;
- (id)closestHitsTo:(struct CGPoint { double x1; double x2; })arg1 withSearchThreshold:(double)arg2 passingTest:(id /* block */)arg3;
- (id)initWithBucketSize:(double)arg1;
- (void)p_addFilledPathToGrid:(id)arg1;
- (void)p_addOpenPathToGrid:(id)arg1;
- (void)p_addPointInfo:(id)arg1;
- (id)p_bucketPointValueForPoint:(struct CGPoint { double x1; double x2; })arg1;
- (void)p_iterateOverEveryBucketPointInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 usingBlock:(id /* block */)arg2;
- (void)p_iterateOverEveryBucketPointNear:(struct CGPoint { double x1; double x2; })arg1 withSearchThreshold:(double)arg2 usingBlock:(id /* block */)arg3;
- (void)p_iterateOverEveryNonEmptyBucketNear:(struct CGPoint { double x1; double x2; })arg1 withSearchThreshold:(double)arg2 usingBlock:(id /* block */)arg3;
- (id)p_pointInfoGridDictionary;
- (id)pathsCrossingPath:(id)arg1 withSearchThreshold:(double)arg2;
- (id)pathsWithPercentage:(double)arg1 approximatelyInsidePath:(id)arg2 requiringPercentForFilledEdges:(bool)arg3;
- (void)removePath:(id)arg1;

@end
