/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSDFreehandDrawingRep : TSDGroupRep

- (id)accessibilityHint;
- (id)accessibilityLabel;
- (id)initWithLayout:(id)arg1 canvas:(id)arg2;
- (bool)isAccessibilityElement;
- (id)p_freehandDrawingInfo;
- (id)p_freehandDrawingLayout;
- (id)textureForDescription:(id)arg1;
- (void)willBeRemoved;

@end
