/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/iWorkImport.framework/iWorkImport
 */

@interface TSKPencilOverlayRenderingDetails : NSObject {
    bool  _isSelected;
    NSMutableArray * _mutableUnscaledSelectionRects;
    struct CGPath { } * _path;
    TSUImage * _rasterizedImage;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _unscaledImageFrame;
}

@property (nonatomic) bool isSelected;
@property (nonatomic, retain) NSMutableArray *mutableUnscaledSelectionRects;
@property (nonatomic) struct CGPath { }*path;
@property (nonatomic, readonly) TSUImage *rasterizedImage;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } unscaledImageFrame;

- (void).cxx_destruct;
- (id)initWithImage:(id)arg1;
- (bool)isSelected;
- (id)mutableUnscaledSelectionRects;
- (struct CGPath { }*)path;
- (id)rasterizedImage;
- (void)setIsSelected:(bool)arg1;
- (void)setMutableUnscaledSelectionRects:(id)arg1;
- (void)setPath:(struct CGPath { }*)arg1;
- (void)setUnscaledImageFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })unscaledImageFrame;

@end
