/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTAsset : NSObject {
    SCNNode * _assetCache;
    AVTAssetInfo * _assetVariants;
    NSString * _bundlePath;
    NSArray * _morphVariants;
    unsigned long long  _numberOfEditableColor;
    unsigned long long  _numberOfModularElements;
    unsigned long long  _refCount;
    long long  _type;
    NSString * _uid;
}

@property (readonly) NSArray *morphVariants;
@property (readonly) unsigned long long numberOfEditableColor;
@property (readonly) unsigned long long numberOfModularElements;
@property (readonly) long long type;
@property (readonly) NSString *uid;

- (void).cxx_destruct;
- (id)assetCacheWithVariant:(long long)arg1 quality:(long long)arg2;
- (id)assetInfoWithVariant:(long long)arg1 quality:(long long)arg2;
- (id)bundlePath;
- (long long)closestQualityOf:(long long)arg1 variant:(long long)arg2;
- (id)componentPathWithAssetInfo:(id)arg1;
- (void)decrUseCount;
- (void)freeCache;
- (void)incrUseCount;
- (id)initWithType:(long long)arg1 path:(id)arg2 packID:(id)arg3;
- (id)morphVariants;
- (unsigned long long)numberOfEditableColor;
- (unsigned long long)numberOfModularElements;
- (void)setAssetCache:(id)arg1 withVariant:(long long)arg2 quality:(long long)arg3;
- (void)setBundlePath:(id)arg1;
- (long long)type;
- (id)uid;

@end
