/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTComponentInstance : NSObject {
    AVTAsset * _asset;
    NSString * _assetImage;
    SCNNode * _assetNode;
    AVTComponent * _component;
    long long  _quality;
    long long  _variant;
}

@property (readonly) NSString *assetImage;
@property (readonly) SCNNode *assetNode;
@property (readonly) AVTComponent *component;
@property (readonly) long long quality;
@property (readonly) long long variant;

+ (id)assetNodeWithPath:(id)arg1;

- (void).cxx_destruct;
- (id)assetImage;
- (id)assetNode;
- (id)component;
- (void)dealloc;
- (id)initWithComponent:(id)arg1 assetInfo:(id)arg2 variant:(long long)arg3 quality:(long long)arg4;
- (long long)quality;
- (void)updateMaterialsWithComponent:(id)arg1;
- (long long)variant;

@end
