/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTComponent : NSObject <AVTLossilyEquatable> {
    AVTAsset * _asset;
    AVTAvatar * _avatar;
    double  _intensity;
    AVTMaterial * _materials;
    unsigned long long  _modularCompositionIndex;
}

@property (readonly) AVTAsset *asset;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) double intensity;
@property (nonatomic) unsigned long long modularCompositionIndex;
@property (readonly) Class superclass;

+ (bool)componentTypeSupportsIntensity:(long long)arg1;
+ (bool)componentTypeSupportsModularComposition:(long long)arg1;
+ (id)componentWithAsset:(id)arg1;
+ (struct UIColor { Class x1; }*)defaultColorAtIndex:(unsigned long long)arg1 forComponentType:(long long)arg2;

- (void).cxx_destruct;
- (bool)_decode:(id)arg1;
- (void)_encode:(id)arg1;
- (id)asset;
- (id)avatar;
- (id)description;
- (id)init;
- (id)initWithAsset:(id)arg1;
- (double)intensity;
- (bool)isLossilyEqual:(id)arg1;
- (bool)isLossilyEqualToComponent:(id)arg1;
- (id)materialAtIndex:(unsigned long long)arg1;
- (unsigned long long)modularCompositionIndex;
- (id)newComponentInstanceWithVariant:(long long)arg1 quality:(long long)arg2;
- (void)setAvatar:(id)arg1;
- (void)setIntensity:(double)arg1;
- (void)setMaterial:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)setModularCompositionIndex:(unsigned long long)arg1;
- (void)setupWithComponent:(id)arg1;

@end
