/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTColorPreset : NSObject {
    unsigned long long  _materialCount;
    AVTMaterial * _materials;
}

+ (id)colorPresetWithMaterials:(id)arg1;

- (void).cxx_destruct;
- (bool)isEqual:(id)arg1;
- (id)materialAtIndex:(unsigned long long)arg1;
- (unsigned long long)materialCount;
- (struct UIImage { Class x1; }*)thumbnail;

@end
