/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTEncodingContext : NSObject {
    char * _data;
    unsigned long long  _dataLength;
    unsigned long long  _offset;
    NSMutableDictionary * _reservedSpace;
    NSMutableArray * packIDs;
    unsigned short  version;
}

@property unsigned short version;

- (void).cxx_destruct;
- (void)addPackID:(id)arg1;
- (unsigned long long)currentOffset;
- (void)encodeBuffer:(void*)arg1 size:(unsigned long long)arg2 forKey:(id)arg3;
- (void)encodeFloat:(float)arg1;
- (void)encodeUint16:(unsigned short)arg1;
- (void)encodeUint32:(unsigned int)arg1;
- (void)encodeUint64:(unsigned long long)arg1;
- (void)encodeUint8:(unsigned char)arg1;
- (id)initForDecodingWithData:(id)arg1;
- (id)initForEncodingWithData:(id)arg1;
- (float)nextFloat;
- (unsigned short)nextUint16;
- (unsigned int)nextUint32;
- (unsigned long long)nextUint64;
- (unsigned char)nextUint8;
- (id)packIDForPackIndex:(unsigned char)arg1;
- (unsigned char)packIndexForPackID:(id)arg1;
- (void)reserveSize:(unsigned long long)arg1 forKey:(id)arg2;
- (void)seekTo:(unsigned long long)arg1;
- (void)setVersion:(unsigned short)arg1;
- (unsigned short)version;

@end
