/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTPuppetGridView : SCNView {
    SCNNode * _cameraTemplate;
    SCNNode * _puppetContainer;
    NSArray * _puppetNames;
    NSMutableArray * _puppets;
}

@property (nonatomic, retain) NSArray *puppetNames;

- (void).cxx_destruct;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)puppetNames;
- (void)setPuppetNames:(id)arg1;
- (void)setupScene;

@end
