/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTPupilReflectionCorrectionDescriptor : NSObject {
    SCNMaterial * _leftEyeMaterial;
    long long  _leftEyeTargetIndex;
    SCNNode * _readMorpherNode;
    SCNMaterial * _rightEyeMaterial;
    long long  _rightEyeTargetIndex;
}

@property (nonatomic) SCNMaterial *leftEyeMaterial;
@property (nonatomic) long long leftEyeTargetIndex;
@property (nonatomic) SCNNode *readMorpherNode;
@property (nonatomic) SCNMaterial *rightEyeMaterial;
@property (nonatomic) long long rightEyeTargetIndex;

- (id)leftEyeMaterial;
- (long long)leftEyeTargetIndex;
- (id)readMorpherNode;
- (id)rightEyeMaterial;
- (long long)rightEyeTargetIndex;
- (void)setLeftEyeMaterial:(id)arg1;
- (void)setLeftEyeTargetIndex:(long long)arg1;
- (void)setReadMorpherNode:(id)arg1;
- (void)setRightEyeMaterial:(id)arg1;
- (void)setRightEyeTargetIndex:(long long)arg1;

@end
