/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTPhysicsRig : NSObject {
    SCNNode * chainRoot;
    void restPosition;
    SCNNode * rig;
}

@property (nonatomic, retain) SCNNode *chainRoot;
@property (nonatomic) void restPosition;
@property (nonatomic, retain) SCNNode *rig;

- (void).cxx_destruct;
- (id)chainRoot;
- (void)restPosition;
- (id)rig;
- (void)setChainRoot:(id)arg1;
- (void)setRestPosition;
- (void)setRig:(id)arg1;

@end
