/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTPhysicalizedMorpherDescriptor : NSObject {
    unsigned long long  _backwardMorphTargetIndex;
    unsigned long long  _downwardMorphTargetIndex;
    SCNNode * _drivingNode;
    unsigned long long  _forwardMorphTargetIndex;
    unsigned long long  _leftwardMorphTargetIndex;
    SCNNode * _referenceNode;
    unsigned long long  _rightwardMorphTargetIndex;
    float  _simulationFactor;
    unsigned long long  _upwardMorphTargetIndex;
    SCNMorpher * _writeMorpher;
}

@property (nonatomic) unsigned long long backwardMorphTargetIndex;
@property (nonatomic) unsigned long long downwardMorphTargetIndex;
@property (nonatomic) SCNNode *drivingNode;
@property (nonatomic) unsigned long long forwardMorphTargetIndex;
@property (nonatomic) unsigned long long leftwardMorphTargetIndex;
@property (nonatomic) SCNNode *referenceNode;
@property (nonatomic) unsigned long long rightwardMorphTargetIndex;
@property (nonatomic) float simulationFactor;
@property (nonatomic) unsigned long long upwardMorphTargetIndex;
@property (nonatomic) SCNMorpher *writeMorpher;

- (unsigned long long)backwardMorphTargetIndex;
- (unsigned long long)downwardMorphTargetIndex;
- (id)drivingNode;
- (unsigned long long)forwardMorphTargetIndex;
- (unsigned long long)leftwardMorphTargetIndex;
- (id)referenceNode;
- (unsigned long long)rightwardMorphTargetIndex;
- (void)setBackwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setDownwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setDrivingNode:(id)arg1;
- (void)setForwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setLeftwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setReferenceNode:(id)arg1;
- (void)setRightwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setSimulationFactor:(float)arg1;
- (void)setUpwardMorphTargetIndex:(unsigned long long)arg1;
- (void)setWriteMorpher:(id)arg1;
- (float)simulationFactor;
- (unsigned long long)upwardMorphTargetIndex;
- (id)writeMorpher;

@end
