/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@interface AVTRig : NSObject <AVTLossilyEquatable> {
    double  _elevation;
    AVTAvatar * _owner;
    double  _rotation;
    double  _scale;
    double  _spacing;
    long long  _type;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property double elevation;
@property (readonly) unsigned long long hash;
@property double rotation;
@property (readonly) long long rotationMode;
@property double scale;
@property (readonly) long long scaleMode;
@property double spacing;
@property (readonly) Class superclass;
@property (readonly) long long type;

- (void)decode:(id)arg1;
- (double)elevation;
- (void)encode:(id)arg1;
- (id)init;
- (id)initWithType:(long long)arg1 avatar:(id)arg2;
- (bool)isLossilyEqual:(id)arg1;
- (bool)isLossilyEqualToRig:(id)arg1;
- (void)randomize;
- (void)resetToDefault;
- (double)rotation;
- (long long)rotationMode;
- (double)scale;
- (long long)scaleMode;
- (void)setElevation:(double)arg1;
- (void)setFromRig:(id)arg1;
- (void)setRotation:(double)arg1;
- (void)setScale:(double)arg1;
- (void)setSpacing:(double)arg1;
- (double)spacing;
- (long long)type;

@end
