/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordServices.framework/HealthRecordServices
 */

@interface HDExtractionResult : NSObject <NSCopying, NSSecureCoding> {
    NSArray * _medicalRecords;
}

@property (nonatomic, readonly, copy) NSArray *medicalRecords;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithMedicalRecords:(id)arg1;
- (id)medicalRecords;

@end
