/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Security.framework/Security
 */

@interface SFTransactionMetric : NSObject <NSSecureCoding> {
    NSString * _category;
    NSObject<OS_os_log> * _logObject;
    NSString * _uuid;
}

@property (nonatomic, copy) NSString *category;
@property (nonatomic, retain) NSObject<OS_os_log> *logObject;
@property (nonatomic, copy) NSString *uuid;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)category;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUUID:(id)arg1 category:(id)arg2;
- (void)logError:(id)arg1;
- (void)logEvent:(id)arg1 eventAttributes:(id)arg2;
- (id)logObject;
- (void)setCategory:(id)arg1;
- (void)setLogObject:(id)arg1;
- (void)setUuid:(id)arg1;
- (id)sftmCreateLogCategory:(id)arg1;
- (id)sftmObjectForCategory:(id)arg1;
- (void)signInCompleted;
- (void)timeEvent:(id)arg1 blockToTime:(id /* block */)arg2;
- (id)uuid;

@end
