/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUINamedRecognitionGroup : CUINamedLookup {
    NSMutableDictionary * _contents;
}

- (void)dealloc;
- (id)initWithName:(id)arg1 contentsFromCatalog:(id)arg2 usingRenditionKey:(id)arg3 fromTheme:(unsigned long long)arg4;
- (id)namedRecognitionImageImageList;
- (id)recognitionImageWithName:(id)arg1;

@end
