/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUINamedRecognitionImage : CUINamedLookup

@property (nonatomic, readonly) int exifOrientation;
@property (nonatomic, readonly) struct CGImage { }*image;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } physicalSizeInMeters;

- (int)exifOrientation;
- (struct CGImage { }*)image;
- (struct CGSize { double x1; double x2; })physicalSizeInMeters;

@end
