/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Home.framework/Home
 */

@interface HFSimpleModuleItemManager : HFItemManager {
    NSArray * _modules;
}

@property (nonatomic, readonly, copy) NSArray *modules;

- (void).cxx_destruct;
- (id)_buildItemProvidersForHome:(id)arg1;
- (id)_buildSectionsWithDisplayedItems:(id)arg1;
- (id)initWithDelegate:(id)arg1 moduleBuilder:(id /* block */)arg2;
- (id)modules;

@end
