/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMAccessorySetupPayload : NSObject {
    HMSetupAccessoryPayload * _internalSetupPayload;
}

@property (retain) HMSetupAccessoryPayload *internalSetupPayload;

- (void).cxx_destruct;
- (id)initWithURL:(id)arg1;
- (id)internalSetupPayload;
- (void)setInternalSetupPayload:(id)arg1;

@end
