/* Generated by RuntimeBrowser.
 */

@protocol CKCloudKitSyncProgressViewControllerDelegate <NSObject>

@required

- (void)cloudKitSyncProgressViewControllerDidChangeVisibility:(CKCloudKitSyncProgressViewController *)arg1;

@end
