/* Generated by RuntimeBrowser.
 */

@protocol MPVolumeControllerDataSource <NSObject>

@required

- (float)EUVolumeLimit;
- (void)adjustVolumeValue:(float)arg1;
- (bool)applicationShouldOverrideHardwareVolumeBehavior;
- (<MPVolumeControllerDataSourceDelegate> *)delegate;
- (bool)isMuted;
- (bool)isVolumeControlAvailable;
- (void)reload;
- (void)reloadWarning;
- (void)setDelegate:(id <MPVolumeControllerDataSourceDelegate>)arg1;
- (void)setMuted:(bool)arg1;
- (void)setVolume:(float)arg1;
- (float)volume;
- (NSString *)volumeControlLabel;
- (bool)volumeWarningEnabled;
- (long long)volumeWarningState;

@end
