/* Generated by RuntimeBrowser.
 */

@protocol MRAVDistantExternalDeviceClientProtocol <NSObject>

@required

- (void)hostedExternalDeviceConnectionStateDidChange:(unsigned int)arg1 withError:(NSError *)arg2;
- (void)hostedExternalDeviceDidReceiveCustomData:(NSData *)arg1 withName:(NSString *)arg2;
- (void)hostedExternalDeviceNameDidChange:(NSString *)arg1;
- (void)hostedExternalDeviceOutputContextDidChangeWithInfo:(struct { unsigned int x1; bool x2; unsigned int x3[2]; })arg1;
- (void)hostedExternalDeviceVolumeDidChange:(float)arg1 forEndpointWithIdentifier:(NSString *)arg2 forOutputDeviceWithIdentifier:(NSString *)arg3;

@end
