/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARImageSensor : NSObject <ARSensor, AVCaptureVideoDataOutputSampleBufferDelegate> {
    AVCaptureDevice * _captureDevice;
    long long  _captureFramesPerSecond;
    NSObject<OS_dispatch_queue> * _captureQueue;
    AVCaptureSession * _captureSession;
    float  _defaultLensPosition;
    <ARSensorDelegate> * _delegate;
    bool  _interrupted;
    unsigned long long  _powerUsage;
    NSObject<OS_dispatch_queue> * _previousOutputCallbackQueue;
    <AVCaptureVideoDataOutputSampleBufferDelegate> * _previousOutputDelegate;
    bool  _previouslyRunning;
    long long  _renderFramesPerSecond;
    bool  _running;
    ARImageSensorSettings * _settings;
    AVCaptureVideoDataOutput * _videoOutput;
}

@property (nonatomic, retain) AVCaptureAudioDataOutput *audioOutput;
@property (nonatomic, readonly) AVCaptureDevice *captureDevice;
@property (readonly) long long captureFramesPerSecond;
@property long long captureFramesPerSecond;
@property (nonatomic, readonly) AVCaptureSession *captureSession;
@property (readonly, copy) NSString *debugDescription;
@property float defaultLensPosition;
@property (nonatomic) <ARSensorDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property bool interrupted;
@property (nonatomic) unsigned long long powerUsage;
@property long long renderFramesPerSecond;
@property (readonly) long long renderFramesPerSecond;
@property bool running;
@property (nonatomic, readonly) ARImageSensorSettings *settings;
@property (readonly) Class superclass;
@property (nonatomic, readonly) AVCaptureVideoDataOutput *videoOutput;

+ (double)closestFrameRateIn:(id)arg1 target:(double)arg2 preferHigher:(bool)arg3;
+ (float)defaultLensPosition;

- (void).cxx_destruct;
- (void)_adjustForPowerUsage;
- (void)_configureCameraExposureForDevice:(id)arg1;
- (void)_configureCameraFocusForDevice:(id)arg1;
- (void)_configureCameraWhiteBalanceForDevice:(id)arg1;
- (id)_createAudioInput:(id*)arg1;
- (bool)_validateCameraAuthorization;
- (id)audioOutput;
- (bool)canReconfigure:(id)arg1;
- (id)captureDevice;
- (long long)captureFramesPerSecond;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg2 fromConnection:(id)arg3;
- (id)captureSession;
- (void)captureSessionStateChanged:(id)arg1;
- (id)configureCaptureDevice;
- (id)configureCaptureSession;
- (void)dealloc;
- (float)defaultLensPosition;
- (id)delegate;
- (void)enableAutoFocusForDevice:(id)arg1;
- (id)init;
- (id)initWithSettings:(id)arg1;
- (bool)interrupted;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (unsigned long long)powerUsage;
- (double)preferredCaptureFrameRateForPowerUsage:(unsigned long long)arg1 devicePosition:(long long)arg2;
- (long long)preferredRenderFrameRateForPowerUsage:(unsigned long long)arg1 devicePosition:(long long)arg2;
- (unsigned long long)providedDataTypes;
- (void)reconfigure:(id)arg1;
- (long long)renderFramesPerSecond;
- (bool)running;
- (void)setAudioOutput:(id)arg1;
- (void)setCaptureFramesPerSecond:(long long)arg1;
- (void)setDefaultLensPosition:(float)arg1;
- (void)setDelegate:(id)arg1;
- (void)setInterrupted:(bool)arg1;
- (void)setPowerUsage:(unsigned long long)arg1;
- (void)setRenderFramesPerSecond:(long long)arg1;
- (void)setRunning:(bool)arg1;
- (id)settings;
- (void)start;
- (void)stop;
- (id)videoOutput;

@end
