/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPlaneEstimationTechnique : ARTechnique {
    NSArray * _anchorIdentifierMap;
    ARCamera * _camera;
    NSObject<OS_dispatch_queue> * _detectionQueue;
    NSObject<OS_dispatch_semaphore> * _detectionSemaphore;
    unsigned long long  _detectionTypeMask;
    ARPlaneData * _planeResultData;
    NSObject<OS_dispatch_semaphore> * _semaphoreResult;
    struct SurfaceDetectionContext { } * _surfaceDetectionHandle;
}

@property unsigned long long detectionTypeMask;

+ (id)_detectPlanesWithDetector:(struct SurfaceDetectionContext { }*)arg1 types:(unsigned long long)arg2 camera:(id)arg3 featurePoints:(id)arg4 inVisionCoordinates:(bool)arg5 singleShot:(bool)arg6;
+ (id)detectPlanes:(unsigned long long)arg1 withFrame:(id)arg2;

- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)detectionTypeMask;
- (id)generateAnchorIdentifiersForCount:(long long)arg1;
- (id)initWithPlaneDetection:(unsigned long long)arg1;
- (id)processData:(id)arg1;
- (void)reconfigureFrom:(id)arg1;
- (void)requestResultDataAtTimestamp:(double)arg1 context:(id)arg2;
- (unsigned long long)requiredSensorDataTypes;
- (id)resultDataClasses;
- (void)setDetectionTypeMask:(unsigned long long)arg1;

@end
