/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARQATracer : NSObject <ARInternalSessionObserver, ARReplaySensorDelegate> {
    unsigned long long  _cameraMovedAtFrame;
    ARQATraceDataBuilder * _dataBuilder;
    <ARQATracerDelegate> * _delegate;
    unsigned long long  _featureCapturedAtFrame;
    unsigned long long  _firstFaceAtFrame;
    unsigned long long  _firstPlaneAtFrame;
    unsigned char  _forceQuitApp;
    unsigned long long  _frameIndex;
    unsigned char  _isTracing;
    struct CGPoint { 
        double x; 
        double y; 
    }  _offset;
    UILabel * _replayFrameLabel;
    ARScreenRecording * _screenRecorder;
    NSString * _traceOutputFilePath;
}

@property (nonatomic, retain) ARQATraceDataBuilder *dataBuilder;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <ARQATracerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) UILabel *replayFrameLabel;
@property (nonatomic, retain) ARScreenRecording *screenRecorder;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSString *traceOutputFilePath;

+ (bool)isEnabled;

- (void).cxx_destruct;
- (void)addFrameLabel:(id)arg1;
- (void)captureFaceData:(id)arg1 frameDataDict:(id)arg2;
- (void)capturePlanesDate:(id)arg1 frameDataDict:(id)arg2;
- (void)createTraceOutputDirectory;
- (id)dataBuilder;
- (id)delegate;
- (id)getARKitVersion;
- (id)getAppleCV3DVersion;
- (id)getSceneKitVersion;
- (void)receiveDefaults;
- (id)replayFrameLabel;
- (void)replaySensorDidFinishReplayingData;
- (id)screenRecorder;
- (void)session:(id)arg1 didChangeState:(unsigned long long)arg2;
- (void)session:(id)arg1 didUpdateFrame:(id)arg2;
- (void)setDataBuilder:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setReplayFrameLabel:(id)arg1;
- (void)setScreenRecorder:(id)arg1;
- (void)setTraceOutputFilePath:(id)arg1;
- (void)start:(id)arg1;
- (void)stop;
- (void)traceARFrame:(id)arg1;
- (void)traceCompleted;
- (id)traceOutputFilePath;
- (void)update:(id)arg1;

@end
