/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARQAJsonBuilder : NSObject {
    NSMutableDictionary * _data;
}

@property (nonatomic, retain) NSMutableDictionary *data;

+ (id)arrayOf3dPoints:(const /* Warning: Unrecognized filer type: '1' using 'void*' */ void**)arg1 count:(unsigned long long)arg2;
+ (id)arrayWithVector3;
+ (id)arrayWithVector4;

- (void).cxx_destruct;
- (void)addWithKey:(id)arg1 value:(id)arg2;
- (id)build;
- (bool)buildAndSave:(id)arg1;
- (id)data;
- (id)init;
- (id)objectForKey:(id)arg1;
- (void)setData:(id)arg1;

@end
