/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARQATraceDataBuilder : ARQAJsonBuilder {
    NSMutableArray * _frames;
    NSMutableDictionary * _header;
    NSMutableDictionary * _summary;
}

@property (nonatomic, retain) NSMutableArray *frames;
@property (nonatomic, retain) NSMutableDictionary *header;
@property (nonatomic, retain) NSMutableDictionary *summary;

- (void).cxx_destruct;
- (void)addFrameDataWithKey:(id)arg1 value:(id)arg2 index:(unsigned long long)arg3;
- (id)frames;
- (id)header;
- (id)init;
- (void)setFrames:(id)arg1;
- (void)setHeader:(id)arg1;
- (void)setSummary:(id)arg1;
- (id)summary;

@end
