/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVWindowRootViewController : UIViewController {
    AVFullScreenViewController * _fullScreenViewController;
    UIWindow * _fullScreenWindow;
}

@property (nonatomic) AVFullScreenViewController *fullScreenViewController;
@property (nonatomic) UIWindow *fullScreenWindow;

- (void).cxx_destruct;
- (bool)_ignoreAppSupportedOrientations;
- (id)fullScreenViewController;
- (id)fullScreenWindow;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)setFullScreenViewController:(id)arg1;
- (void)setFullScreenWindow:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;

@end
