/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVKit.framework/AVKit
 */

@interface AVWindow : UIWindow {
    AVFullScreenViewController * _fullScreenViewController;
    AVPlayerViewController * _playerViewController;
    UIWindow * _sourceWindow;
}

@property (nonatomic, readonly) AVFullScreenViewController *fullScreenViewController;
@property (nonatomic, retain) AVPlayerViewController *playerViewController;
@property (nonatomic, readonly) UIWindow *sourceWindow;

- (void).cxx_destruct;
- (unsigned long long)_supportedInterfaceOrientationsForRootViewController;
- (void)dealloc;
- (id)fullScreenViewController;
- (id)initWithPlayerViewController:(id)arg1;
- (id)playerViewController;
- (void)setPlayerViewController:(id)arg1;
- (id)sourceWindow;

@end
