/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@interface AXSubsystemAppAX : AXLoggingSubsystem

+ (id)identifier;

@end
