/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFConfigurationSourceClient : NSObject <DMFConfigurationSourceClientInterface, NSXPCConnectionDelegate, NSXPCListenerDelegate> {
    DMFConnection * _connection;
    <DMFConfigurationSourceClientDelegate> * _delegate;
    NSXPCConnection * _incomingConnection;
    bool  _invalid;
    NSXPCListener * _listener;
    CATOperationQueue * _operationQueue;
    DMFRegisterConfigurationSourceRequest * _registrationRequest;
    NSObject<OS_dispatch_queue> * _serialQueue;
    DMFStatusReportingRequirements * _statusReportingRequirements;
}

@property (nonatomic, retain) DMFConnection *connection;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <DMFConfigurationSourceClientDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSXPCConnection *incomingConnection;
@property (getter=isInvalid, nonatomic) bool invalid;
@property (nonatomic, retain) NSXPCListener *listener;
@property (nonatomic, retain) CATOperationQueue *operationQueue;
@property (nonatomic, retain) DMFRegisterConfigurationSourceRequest *registrationRequest;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *serialQueue;
@property (nonatomic, retain) DMFStatusReportingRequirements *statusReportingRequirements;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)assetResolutionOperationDidFinish:(id)arg1 completion:(id /* block */)arg2;
- (void)configurationEngineRequestedAsset:(id)arg1 completion:(id /* block */)arg2;
- (void)configurationStatusDidChange:(id)arg1 completion:(id /* block */)arg2;
- (id)connection;
- (void)dealloc;
- (id)delegate;
- (id)description;
- (void)enqueueOperationToReportStatusChange:(id)arg1 completion:(id /* block */)arg2;
- (void)enqueueOperationToResolveAsset:(id)arg1 completion:(id /* block */)arg2;
- (id)incomingConnection;
- (id)init;
- (id)initWithConnection:(id)arg1 organizationIdentifier:(id)arg2 displayName:(id)arg3 localMachServiceName:(id)arg4;
- (void)invalidate;
- (bool)isInvalid;
- (id)listener;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)machService;
- (id)name;
- (void)operationDidStart:(id)arg1;
- (id)operationQueue;
- (void)probe:(id /* block */)arg1;
- (void)registerConfigurationSource;
- (void)registrationOperationDidFinish:(id)arg1;
- (id)registrationRequest;
- (void)resume;
- (id)serialQueue;
- (void)setConnection:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setIncomingConnection:(id)arg1;
- (void)setInvalid:(bool)arg1;
- (void)setListener:(id)arg1;
- (void)setOperationQueue:(id)arg1;
- (void)setRegistrationRequest:(id)arg1;
- (void)setSerialQueue:(id)arg1;
- (void)setStatusReportingRequirements:(id)arg1;
- (void)statusReportingOperationDidFinish:(id)arg1 completion:(id /* block */)arg2;
- (id)statusReportingRequirements;

@end
