/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFEnrollProvisionallyInDeviceEnrollmentProgramRequest : CATTaskRequest {
    NSString * _nonce;
}

@property (nonatomic, copy) NSString *nonce;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)nonce;
- (void)setNonce:(id)arg1;

@end
