/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFEndTransactionRequest : CATTaskRequest {
    NSUUID * _UUID;
}

@property (nonatomic, retain) NSUUID *UUID;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)UUID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setUUID:(id)arg1;

@end
