/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFFetchOrganizationsRequest : CATTaskRequest

+ (bool)supportsSecureCoding;
+ (Class)whitelistedClassForResultObject;

@end
