/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFFetchDeclarationsResultObject : CATTaskResultObject {
    NSArray * _payloadContents;
    NSArray * _payloadDescriptions;
}

@property (nonatomic, copy) NSArray *payloadContents;
@property (nonatomic, copy) NSArray *payloadDescriptions;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)payloadContents;
- (id)payloadDescriptions;
- (void)setPayloadContents:(id)arg1;
- (void)setPayloadDescriptions:(id)arg1;

@end
