/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFFetchOSUpdateStatusRequest : CATTaskRequest

+ (Class)whitelistedClassForResultObject;

@end
