/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFStatusReportingRequirements : NSObject <NSSecureCoding> {
    NSString * _reachableHostName;
    bool  _requireActiveConnection;
    double  _statusUpdateCoalescenceInterval;
}

@property (nonatomic, copy) NSString *reachableHostName;
@property (nonatomic) bool requireActiveConnection;
@property (nonatomic) double statusUpdateCoalescenceInterval;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)reachableHostName;
- (bool)requireActiveConnection;
- (void)setReachableHostName:(id)arg1;
- (void)setRequireActiveConnection:(bool)arg1;
- (void)setStatusUpdateCoalescenceInterval:(double)arg1;
- (double)statusUpdateCoalescenceInterval;

@end
