/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFSetupSharingService : NSObject {
    SFSession * _activeSession;
    id /* block */  _configurationReceivedHandler;
    id /* block */  _preAuthorizationReceivedHandler;
    SFClient * _preventExitForLocaleClient;
    id /* block */  _progressHandler;
    SFService * _service;
    id /* block */  _serviceCompletionHandler;
}

@property (nonatomic, retain) SFSession *activeSession;
@property (nonatomic, copy) id /* block */ configurationReceivedHandler;
@property (nonatomic, readonly) NSObject<OS_os_log> *log;
@property (nonatomic, copy) id /* block */ preAuthorizationReceivedHandler;
@property (nonatomic, readonly) SFClient *preventExitForLocaleClient;
@property (nonatomic, copy) id /* block */ progressHandler;
@property (nonatomic, readonly) SFService *service;
@property (nonatomic, copy) id /* block */ serviceCompletionHandler;

- (void).cxx_destruct;
- (void)_handleBasicConfigurationRequest:(id)arg1 responseHandler:(id /* block */)arg2;
- (void)_handleEnrollConfiguratorRequest:(id)arg1 responseHandler:(id /* block */)arg2;
- (void)_handlePreAuthorizationRequest:(id)arg1 responseHandler:(id /* block */)arg2;
- (void)_handleProvisionallyEnrollInDEPRequest:(id)arg1 responseHandler:(id /* block */)arg2;
- (void)_serviceCompletedWithError:(id)arg1;
- (void)_sessionEnded:(id)arg1 withError:(id)arg2;
- (void)_sessionSecured:(id)arg1;
- (void)_sessionStarted:(id)arg1;
- (id)activeSession;
- (void)beginServiceWithShowPINHandler:(id /* block */)arg1;
- (id /* block */)configurationReceivedHandler;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)init;
- (id)initWithHandlerQueue:(id)arg1;
- (void)invalidate;
- (id)log;
- (id /* block */)preAuthorizationReceivedHandler;
- (id)preventExitForLocaleClient;
- (id /* block */)progressHandler;
- (id)service;
- (id /* block */)serviceCompletionHandler;
- (void)setActiveSession:(id)arg1;
- (void)setConfigurationReceivedHandler:(id /* block */)arg1;
- (void)setPreAuthorizationReceivedHandler:(id /* block */)arg1;
- (void)setProgressHandler:(id /* block */)arg1;
- (void)setServiceCompletionHandler:(id /* block */)arg1;

@end
