/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFSetAppVPNUUIDRequest : DMFAppRequest {
    NSString * _UUIDString;
}

@property (nonatomic, copy) NSString *UUIDString;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)UUIDString;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setUUIDString:(id)arg1;

@end
