/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFUnregisterUserAgentRequest : CATTaskRequest {
    NSString * _appleID;
}

@property (nonatomic, copy) NSString *appleID;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)appleID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setAppleID:(id)arg1;

@end
