/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingTarget : HMFObject {
    NSArray * _others;
    HMDAccessory * _primary;
}

@property (nonatomic, readonly) NSArray *others;
@property (nonatomic, readonly) HMDAccessory *primary;

- (void).cxx_destruct;
- (id)initWithAccessory:(id)arg1;
- (id)initWithMediaSystem:(id)arg1;
- (id)others;
- (id)primary;

@end
