/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingUpdateSecondarySender : HMDAccessorySettingUpdateBase

+ (id)logCategory;

- (id)description;
- (void)updateWithConfigurationVersion:(unsigned long long)arg1;

@end
