/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingUpdateOnAccessoryInitiator : HMDAccessorySettingUpdateInitiator

+ (id)logCategory;

- (id)description;
- (void)update;

@end
