/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingUpdateRelayInitiator : HMDAccessorySettingUpdateInitiator

+ (id)logCategory;

- (void)_handleRemoteResponse:(id)arg1 responsePayload:(id)arg2;
- (id)description;
- (void)update;

@end
