/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAccessorySettingUpdateInitiator : HMDAccessorySettingUpdateBase <HMDAccessorySettingUpdateDelegate> {
    HMDAccessorySettingUpdateSecondarySender * _secondarySender;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) HMDAccessorySettingUpdateSecondarySender *secondarySender;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)createSecondarySender:(unsigned long long)arg1;
- (id)description;
- (id)secondarySender;
- (void)setSecondarySender:(id)arg1;
- (void)settingUpdate:(id)arg1 didCompleteWithError:(id)arg2;

@end
