/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitSyncingProgressTestUploading : IMCloudKitSyncingProgressTest

- (void)updateSyncState:(id)arg1;

@end
