/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitSyncingProgressTest : IMCloudKitEventNotificationTest {
    int  _count;
    int  _counter;
}

- (void)startTest;
- (void)updateMockStateForProgressPolling;
- (void)updateSyncState:(id)arg1;

@end
