/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
 */

@interface IMCloudKitEventNotificationRuntimeTestSuite : IMRuntimeTestSuite

+ (void)runTestSuiteWithRepeat:(bool)arg1;
+ (void)runTestsIfNeededWithRepeat:(bool)arg1;

- (id)init;

@end
