/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface _AFClientConfigurationMutation : NSObject <AFClientConfigurationMutating> {
    AFClientConfiguration * _baseModel;
    bool  _isDeviceInCarDNDMode;
    bool  _isDeviceInSetupFlow;
    struct _mutationFlags { 
        unsigned int isDirty : 1; 
        unsigned int hasIsDeviceInSetupFlow : 1; 
        unsigned int hasIsDeviceInCarDNDMode : 1; 
        unsigned int hasTapToSiriAudioPlaybackRequest : 1; 
        unsigned int hasTwoShotAudioPlaybackRequest : 1; 
    }  _mutationFlags;
    AFAudioPlaybackRequest * _tapToSiriAudioPlaybackRequest;
    AFAudioPlaybackRequest * _twoShotAudioPlaybackRequest;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)generate;
- (id)init;
- (id)initWithBaseModel:(id)arg1;
- (void)setIsDeviceInCarDNDMode:(bool)arg1;
- (void)setIsDeviceInSetupFlow:(bool)arg1;
- (void)setTapToSiriAudioPlaybackRequest:(id)arg1;
- (void)setTwoShotAudioPlaybackRequest:(id)arg1;

@end
