/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/BusinessChat.framework/BusinessChat
 */

@interface BCMessage : NSObject <BCMessageProtocol> {
    NSString * _accessibilityLabel;
    NSData * _data;
    UIImage * _image;
    bool  _isFromMe;
    NSString * _messageGUID;
    long long  _style;
    NSString * _subcaption;
    NSAttributedString * _subtitle;
    NSString * _summaryText;
    NSString * _title;
    long long  _type;
    NSURL * _url;
}

@property (nonatomic, retain) NSString *accessibilityLabel;
@property (nonatomic, readonly) NSData *data;
@property (nonatomic, readonly) UIImage *image;
@property (nonatomic, readonly) bool isFromMe;
@property (nonatomic, readonly) NSString *messageGUID;
@property (nonatomic, readonly) long long style;
@property (nonatomic, retain) NSString *subcaption;
@property (nonatomic, retain) NSAttributedString *subtitle;
@property (nonatomic, retain) NSString *summaryText;
@property (nonatomic, retain) NSString *title;
@property (nonatomic, readonly) long long type;
@property (nonatomic, readonly) NSURL *url;

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (id)data;
- (id)image;
- (id)initWithData:(id)arg1 url:(id)arg2 messageGUID:(id)arg3 isFromMe:(bool)arg4;
- (bool)isFromMe;
- (id)messageGUID;
- (void)setAccessibilityLabel:(id)arg1;
- (void)setSubcaption:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setSummaryText:(id)arg1;
- (void)setTitle:(id)arg1;
- (long long)style;
- (id)subcaption;
- (id)subtitle;
- (id)summaryText;
- (id)title;
- (long long)type;
- (id)url;

@end
