/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClockKitUI.framework/ClockKitUI
 */

@interface CLKUIMetalQuad : CLKUIQuad {
    unsigned int  _isPrepared;
    <MTLRenderPipelineState> * _renderPipelineState;
    <MTLBuffer> * _uniformBuffer;
    <MTLBuffer> * _vertexBuffer;
}

- (void).cxx_destruct;
- (id)_newRenderPipelineStateOpaque:(bool)arg1;
- (void)_prepare;
- (void)_purge;
- (void)encode:(id)arg1;
- (void)setOpaque:(bool)arg1;

@end
