/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClockKitUI.framework/ClockKitUI
 */

@interface CLKUIGLQuad : CLKUIQuad {
    unsigned int  _isPrepared;
    unsigned int  _primaryTexture;
    CLKUIGLProgram * _program;
    unsigned int  _secondaryTexture;
    unsigned int  _vertexArray;
    unsigned int  _vertexBuffer;
}

- (void).cxx_destruct;
- (void)_createVertexArray;
- (void)_deleteVertexArray;
- (void)_prepare;
- (void)_purge;
- (void)encode;

@end
