/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
 */

@interface ASDAppUsageStore : NSObject {
    ASDAppUsageStats * _leastUsageCount;
    ASDAppUsageStats * _leastUsageTime;
    ASDAppUsageStats * _topUsageCount;
    ASDAppUsageStats * _topUsageTime;
    NSArray * _usageStats;
}

@property (nonatomic, readonly) ASDAppUsageStats *leastUsageCount;
@property (nonatomic, readonly) ASDAppUsageStats *leastUsageTime;
@property (nonatomic, readonly) ASDAppUsageStats *topUsageCount;
@property (nonatomic, readonly) ASDAppUsageStats *topUsageTime;
@property (nonatomic, readonly) NSArray *usageStats;

- (void).cxx_destruct;
- (void)_calculateUsageForDurationInDays:(double)arg1 bundleIDs:(id)arg2;
- (id)_sortDescriptors;
- (id)initWithDurationInDays:(double)arg1 bundleIDs:(id)arg2;
- (id)leastUsageCount;
- (id)leastUsageTime;
- (id)topUsageCount;
- (id)topUsageTime;
- (id)usageStats;

@end
