/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
 */

@interface ASDAppUsageStats : NSObject <NSCopying> {
    NSString * _bundleID;
    long long  _usageCount;
    double  _usageTime;
}

@property (nonatomic, copy) NSString *bundleID;
@property (nonatomic) long long usageCount;
@property (nonatomic) double usageTime;

- (void).cxx_destruct;
- (id)bundleID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)formatTime:(long long)arg1;
- (void)setBundleID:(id)arg1;
- (void)setUsageCount:(long long)arg1;
- (void)setUsageTime:(double)arg1;
- (long long)usageCount;
- (double)usageTime;

@end
