/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAssetBase : CEMDeclarationBase

+ (id)Descriptor_allowedPayloadKeys;
+ (id)Reference_allowedPayloadKeys;
+ (id)declarationClass;

- (id)serializePayloadDescriptor:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadReference:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDescriptor_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validPayloadReference_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;

@end
