/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAccountCardDAVDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadCardDAVAccountDescription;
@property (nonatomic, readonly) NSString *payloadCardDAVCredentials;
@property (nonatomic, readonly) NSString *payloadCardDAVHostName;
@property (nonatomic, readonly) NSNumber *payloadCardDAVPort;
@property (nonatomic, readonly) NSString *payloadCardDAVPrincipalURL;
@property (nonatomic, readonly) NSNumber *payloadCardDAVUseSSL;
@property (nonatomic, readonly) NSDictionary *payloadCommunicationServiceRules;
@property (readonly) Class superclass;

+ (id)CommunicationServiceRules_DefaultServiceHandlers_allowedPayloadKeys;
+ (id)CommunicationServiceRules_allowedPayloadKeys;
+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadCardDAVAccountDescription;
- (id)payloadCardDAVCredentials;
- (id)payloadCardDAVHostName;
- (id)payloadCardDAVPort;
- (id)payloadCardDAVPrincipalURL;
- (id)payloadCardDAVUseSSL;
- (id)payloadCommunicationServiceRules;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadCommunicationServiceRules:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadCommunicationServiceRules_DefaultServiceHandlers:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadCommunicationServiceRules_DefaultServiceHandlers_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validPayloadCommunicationServiceRules_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
