/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMApplicationStoreDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowAppInstallation;
@property (nonatomic, readonly) NSNumber *payloadAllowAppRemoval;
@property (nonatomic, readonly) NSNumber *payloadAllowAutomaticAppDownloads;
@property (nonatomic, readonly) NSNumber *payloadAllowInAppPurchases;
@property (nonatomic, readonly) NSNumber *payloadAllowSystemAppRemoval;
@property (nonatomic, readonly) NSNumber *payloadAllowUIAppInstallation;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowAppInstallation;
- (id)payloadAllowAppRemoval;
- (id)payloadAllowAutomaticAppDownloads;
- (id)payloadAllowInAppPurchases;
- (id)payloadAllowSystemAppRemoval;
- (id)payloadAllowUIAppInstallation;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
