/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAccountWebClipDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadFullScreen;
@property (nonatomic, readonly) NSString *payloadIcon;
@property (nonatomic, readonly) NSNumber *payloadIsRemovable;
@property (nonatomic, readonly) NSString *payloadLabel;
@property (nonatomic, readonly) NSNumber *payloadPrecomposed;
@property (nonatomic, readonly) NSString *payloadURL;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadFullScreen;
- (id)payloadIcon;
- (id)payloadIsRemovable;
- (id)payloadLabel;
- (id)payloadPrecomposed;
- (id)payloadURL;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
