/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAccountCalDAVDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadCalDAVAccountDescription;
@property (nonatomic, readonly) NSString *payloadCalDAVCredentials;
@property (nonatomic, readonly) NSString *payloadCalDAVHostName;
@property (nonatomic, readonly) NSNumber *payloadCalDAVPort;
@property (nonatomic, readonly) NSString *payloadCalDAVPrincipalURL;
@property (nonatomic, readonly) NSNumber *payloadCalDAVUseSSL;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadCalDAVAccountDescription;
- (id)payloadCalDAVCredentials;
- (id)payloadCalDAVHostName;
- (id)payloadCalDAVPort;
- (id)payloadCalDAVPrincipalURL;
- (id)payloadCalDAVUseSSL;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
