/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMApplicationInstallDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadApplication;
@property (nonatomic, readonly) NSDictionary *payloadConfiguration;
@property (nonatomic, readonly) NSNumber *payloadInstallWhenActivated;
@property (nonatomic, readonly) NSNumber *payloadManageData;
@property (nonatomic, readonly) NSNumber *payloadMandatory;
@property (nonatomic, readonly) NSNumber *payloadPreventDataBackup;
@property (nonatomic, readonly) NSNumber *payloadRemoveWhenDeactivated;
@property (nonatomic, readonly) NSString *payloadVPNUUID;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadApplication;
- (id)payloadConfiguration;
- (id)payloadInstallWhenActivated;
- (id)payloadManageData;
- (id)payloadMandatory;
- (id)payloadPreventDataBackup;
- (id)payloadRemoveWhenDeactivated;
- (id)payloadVPNUUID;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
