/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMAccountMailDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowMailDrop;
@property (nonatomic, readonly) NSNumber *payloadDisableMailRecentsSyncing;
@property (nonatomic, readonly) NSString *payloadEmailAccountDescription;
@property (nonatomic, readonly) NSString *payloadEmailAccountName;
@property (nonatomic, readonly) NSString *payloadEmailAccountType;
@property (nonatomic, readonly) NSString *payloadEmailAddress;
@property (nonatomic, readonly) NSString *payloadIncomingCredentials;
@property (nonatomic, readonly) NSString *payloadIncomingMailServerAuthentication;
@property (nonatomic, readonly) NSString *payloadIncomingMailServerHostName;
@property (nonatomic, readonly) NSString *payloadIncomingMailServerIMAPPathPrefix;
@property (nonatomic, readonly) NSNumber *payloadIncomingMailServerPortNumber;
@property (nonatomic, readonly) NSNumber *payloadIncomingMailServerUseSSL;
@property (nonatomic, readonly) NSString *payloadOutgoingCredentials;
@property (nonatomic, readonly) NSString *payloadOutgoingMailServerAuthentication;
@property (nonatomic, readonly) NSNumber *payloadOutgoingMailServerPortNumber;
@property (nonatomic, readonly) NSNumber *payloadOutgoingMailServerUseSSL;
@property (nonatomic, readonly) NSString *payloadOutgoingMailServerUsername;
@property (nonatomic, readonly) NSNumber *payloadOutgoingPasswordSameAsIncomingPassword;
@property (nonatomic, readonly) NSNumber *payloadPreventAppSheet;
@property (nonatomic, readonly) NSNumber *payloadPreventMove;
@property (nonatomic, readonly) NSNumber *payloadSMIMEEnablePerMessageSwitch;
@property (nonatomic, readonly) NSNumber *payloadSMIMEEnabled;
@property (nonatomic, readonly) NSString *payloadSMIMEEncryptionCertificateUUID;
@property (nonatomic, readonly) NSNumber *payloadSMIMEEncryptionEnabled;
@property (nonatomic, readonly) NSString *payloadSMIMESigningCertificateUUID;
@property (nonatomic, readonly) NSNumber *payloadSMIMESigningEnabled;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowMailDrop;
- (id)payloadDisableMailRecentsSyncing;
- (id)payloadEmailAccountDescription;
- (id)payloadEmailAccountName;
- (id)payloadEmailAccountType;
- (id)payloadEmailAddress;
- (id)payloadIncomingCredentials;
- (id)payloadIncomingMailServerAuthentication;
- (id)payloadIncomingMailServerHostName;
- (id)payloadIncomingMailServerIMAPPathPrefix;
- (id)payloadIncomingMailServerPortNumber;
- (id)payloadIncomingMailServerUseSSL;
- (id)payloadOutgoingCredentials;
- (id)payloadOutgoingMailServerAuthentication;
- (id)payloadOutgoingMailServerPortNumber;
- (id)payloadOutgoingMailServerUseSSL;
- (id)payloadOutgoingMailServerUsername;
- (id)payloadOutgoingPasswordSameAsIncomingPassword;
- (id)payloadPreventAppSheet;
- (id)payloadPreventMove;
- (id)payloadSMIMEEnablePerMessageSwitch;
- (id)payloadSMIMEEnabled;
- (id)payloadSMIMEEncryptionCertificateUUID;
- (id)payloadSMIMEEncryptionEnabled;
- (id)payloadSMIMESigningCertificateUUID;
- (id)payloadSMIMESigningEnabled;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
