/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMApplicationStoreMacOSDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadDisableSoftwareUpdateNotifications;
@property (nonatomic, readonly) NSNumber *payloadRestrictStoreDisableAppAdoption;
@property (nonatomic, readonly) NSNumber *payloadRestrictStoreMdmInstallSoftwareupdateOnly;
@property (nonatomic, readonly) NSNumber *payloadRestrictStoreRequireAdminToInstall;
@property (nonatomic, readonly) NSNumber *payloadRestrictStoreSoftwareupdateOnly;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadDisableSoftwareUpdateNotifications;
- (id)payloadRestrictStoreDisableAppAdoption;
- (id)payloadRestrictStoreMdmInstallSoftwareupdateOnly;
- (id)payloadRestrictStoreRequireAdminToInstall;
- (id)payloadRestrictStoreSoftwareupdateOnly;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
