/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMClassroomRequestMirroringCommand : CEMCommandBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadDestinationDeviceID;
@property (nonatomic, readonly) NSString *payloadDestinationName;
@property (nonatomic, readonly) NSString *payloadPassword;
@property (nonatomic, readonly) NSNumber *payloadScanTime;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)registeredClass;
+ (id)registeredType;

- (int)executionLevel;
- (bool)mustBeSupervised;
- (id)payloadDestinationDeviceID;
- (id)payloadDestinationName;
- (id)payloadPassword;
- (id)payloadScanTime;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
