/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMCommandBase : CEMPayloadBase {
    NSString * _commandDescription;
    NSString * _commandIdentifier;
    NSDictionary * _commandPayload;
    NSNumber * _commandRequiresNetworkTether;
    NSString * _commandType;
}

@property (nonatomic, readonly) NSString *commandDescription;
@property (nonatomic, readonly) NSString *commandIdentifier;
@property (nonatomic, readonly) NSDictionary *commandPayload;
@property (nonatomic, readonly) NSNumber *commandRequiresNetworkTether;
@property (nonatomic, readonly) NSString *commandType;

+ (id)commandForPayload:(id)arg1 error:(id*)arg2;

- (void).cxx_destruct;
- (id)commandDescription;
- (id)commandIdentifier;
- (id)commandPayload;
- (id)commandRequiresNetworkTether;
- (id)commandType;
- (int)executionLevel;
- (bool)loadCommandFromDictionary:(id)arg1 error:(id*)arg2;
- (bool)mustBeSupervised;
- (id)serialize;
- (id)serializePayload:(id)arg1;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;

@end
