/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMDeclarationBase : CEMPayloadBase {
    NSString * _declarationActivationScope;
    NSString * _declarationDescription;
    NSString * _declarationIdentifier;
    NSDictionary * _declarationPayload;
    NSNumber * _declarationRequiresNetworkTether;
    NSString * _declarationServerHash;
    NSString * _declarationType;
}

@property (nonatomic, readonly) NSString *declarationActivationScope;
@property (nonatomic, readonly) NSString *declarationDescription;
@property (nonatomic, readonly) NSString *declarationIdentifier;
@property (nonatomic, readonly) NSDictionary *declarationPayload;
@property (nonatomic, readonly) NSNumber *declarationRequiresNetworkTether;
@property (nonatomic, readonly) NSString *declarationServerHash;
@property (nonatomic, readonly) NSString *declarationType;

+ (id)declarationClass;
+ (id)declarationForPayload:(id)arg1 error:(id*)arg2;

- (void).cxx_destruct;
- (id)declarationActivationScope;
- (id)declarationDescription;
- (id)declarationIdentifier;
- (id)declarationPayload;
- (id)declarationRequiresNetworkTether;
- (id)declarationServerHash;
- (id)declarationType;
- (bool)loadDeclarationFromDictionary:(id)arg1 error:(id*)arg2;
- (id)serialize;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;

@end
