/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMManagementConnectionCommand : CEMCommandBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSArray *payloadCertificates;
@property (nonatomic, readonly) NSString *payloadCheckInURL;
@property (nonatomic, readonly) NSArray *payloadCheckInURLPinningCertificateUUIDs;
@property (nonatomic, readonly) NSString *payloadControlURL;
@property (nonatomic, readonly) NSArray *payloadControlURLPinningCertificateUUIDs;
@property (nonatomic, readonly) NSString *payloadIdentityCertificateUUID;
@property (nonatomic, readonly) NSNumber *payloadPinningRevocationCheckRequired;
@property (nonatomic, readonly) NSNumber *payloadSignMessage;
@property (nonatomic, readonly) NSString *payloadStatusURL;
@property (nonatomic, readonly) NSArray *payloadStatusURLPinningCertificateUUIDs;
@property (nonatomic, readonly) NSString *payloadTopic;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)registeredClass;
+ (id)registeredType;

- (int)executionLevel;
- (bool)mustBeSupervised;
- (id)payloadCertificates;
- (id)payloadCheckInURL;
- (id)payloadCheckInURLPinningCertificateUUIDs;
- (id)payloadControlURL;
- (id)payloadControlURLPinningCertificateUUIDs;
- (id)payloadIdentityCertificateUUID;
- (id)payloadPinningRevocationCheckRequired;
- (id)payloadSignMessage;
- (id)payloadStatusURL;
- (id)payloadStatusURLPinningCertificateUUIDs;
- (id)payloadTopic;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
