/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMNetworkGlobalHTTPProxyDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadProxyCaptiveLoginAllowed;
@property (nonatomic, readonly) NSNumber *payloadProxyPACFallbackAllowed;
@property (nonatomic, readonly) NSString *payloadProxyPACURL;
@property (nonatomic, readonly) NSString *payloadProxyPassword;
@property (nonatomic, readonly) NSString *payloadProxyServer;
@property (nonatomic, readonly) NSNumber *payloadProxyServerPort;
@property (nonatomic, readonly) NSString *payloadProxyType;
@property (nonatomic, readonly) NSString *payloadProxyUsername;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadProxyCaptiveLoginAllowed;
- (id)payloadProxyPACFallbackAllowed;
- (id)payloadProxyPACURL;
- (id)payloadProxyPassword;
- (id)payloadProxyServer;
- (id)payloadProxyServerPort;
- (id)payloadProxyType;
- (id)payloadProxyUsername;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
