/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMNetworkWiFiDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAutoJoin;
@property (nonatomic, readonly) NSNumber *payloadCaptiveBypass;
@property (nonatomic, readonly) NSString *payloadDisplayedOperatorName;
@property (nonatomic, readonly) NSString *payloadDomainName;
@property (nonatomic, readonly) NSDictionary *payloadEAPClientConfiguration;
@property (nonatomic, readonly) NSNumber *payloadEnableIPv6;
@property (nonatomic, readonly) NSString *payloadEncryptionType;
@property (nonatomic, readonly) NSString *payloadHESSID;
@property (nonatomic, readonly) NSNumber *payloadHIDDENNETWORK;
@property (nonatomic, readonly) NSString *payloadInterface;
@property (nonatomic, readonly) NSNumber *payloadIsHotspot;
@property (nonatomic, readonly) NSArray *payloadMCCAndMNCs;
@property (nonatomic, readonly) NSArray *payloadNAIRealmNames;
@property (nonatomic, readonly) NSString *payloadNONEXISTENT;
@property (nonatomic, readonly) NSString *payloadPassword;
@property (nonatomic, readonly) NSString *payloadPayloadCertificateUUID;
@property (nonatomic, readonly) NSNumber *payloadPriority;
@property (nonatomic, readonly) NSNumber *payloadProxyPACFallbackAllowed;
@property (nonatomic, readonly) NSString *payloadProxyPACURL;
@property (nonatomic, readonly) NSString *payloadProxyPassword;
@property (nonatomic, readonly) NSString *payloadProxyServer;
@property (nonatomic, readonly) NSNumber *payloadProxyServerPort;
@property (nonatomic, readonly) NSString *payloadProxyType;
@property (nonatomic, readonly) NSString *payloadProxyUsername;
@property (nonatomic, readonly) NSDictionary *payloadQoSMarkingPolicy;
@property (nonatomic, readonly) NSArray *payloadRoamingConsortiumOIs;
@property (nonatomic, readonly) NSString *payloadSSIDSTR;
@property (nonatomic, readonly) NSNumber *payloadServiceProviderRoamingEnabled;
@property (nonatomic, readonly) NSArray *payloadSetupModes;
@property (nonatomic, readonly) NSNumber *payloadTLSCertificateRequired;
@property (readonly) Class superclass;

+ (id)EAPClientConfiguration_allowedPayloadKeys;
+ (id)QoSMarkingPolicy_allowedPayloadKeys;
+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAutoJoin;
- (id)payloadCaptiveBypass;
- (id)payloadDisplayedOperatorName;
- (id)payloadDomainName;
- (id)payloadEAPClientConfiguration;
- (id)payloadEnableIPv6;
- (id)payloadEncryptionType;
- (id)payloadHESSID;
- (id)payloadHIDDENNETWORK;
- (id)payloadInterface;
- (id)payloadIsHotspot;
- (id)payloadMCCAndMNCs;
- (id)payloadNAIRealmNames;
- (id)payloadNONEXISTENT;
- (id)payloadPassword;
- (id)payloadPayloadCertificateUUID;
- (id)payloadPriority;
- (id)payloadProxyPACFallbackAllowed;
- (id)payloadProxyPACURL;
- (id)payloadProxyPassword;
- (id)payloadProxyServer;
- (id)payloadProxyServerPort;
- (id)payloadProxyType;
- (id)payloadProxyUsername;
- (id)payloadQoSMarkingPolicy;
- (id)payloadRoamingConsortiumOIs;
- (id)payloadSSIDSTR;
- (id)payloadServiceProviderRoamingEnabled;
- (id)payloadSetupModes;
- (id)payloadTLSCertificateRequired;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadEAPClientConfiguration:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadQoSMarkingPolicy:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validPayloadEAPClientConfiguration_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validPayloadQoSMarkingPolicy_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
