/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMPasscodeSettingsDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowAutoUnlock;
@property (nonatomic, readonly) NSNumber *payloadAllowFingerprintForUnlock;
@property (nonatomic, readonly) NSNumber *payloadAllowFingerprintModification;
@property (nonatomic, readonly) NSNumber *payloadAllowPasscodeModification;
@property (nonatomic, readonly) NSNumber *payloadAllowSimple;
@property (nonatomic, readonly) NSNumber *payloadChangeAtNextAuth;
@property (nonatomic, readonly) NSNumber *payloadForcePIN;
@property (nonatomic, readonly) NSNumber *payloadManualFetchingWhenRoaming;
@property (nonatomic, readonly) NSNumber *payloadMaxFailedAttempts;
@property (nonatomic, readonly) NSNumber *payloadMaxGracePeriod;
@property (nonatomic, readonly) NSNumber *payloadMaxInactivity;
@property (nonatomic, readonly) NSNumber *payloadMaxPINAgeInDays;
@property (nonatomic, readonly) NSNumber *payloadMinComplexChars;
@property (nonatomic, readonly) NSNumber *payloadMinLength;
@property (nonatomic, readonly) NSNumber *payloadMinutesUntilFailedLoginReset;
@property (nonatomic, readonly) NSNumber *payloadPasscodeLockGracePeriod;
@property (nonatomic, readonly) NSNumber *payloadPinHistory;
@property (nonatomic, readonly) NSNumber *payloadRequireAlphanumeric;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowAutoUnlock;
- (id)payloadAllowFingerprintForUnlock;
- (id)payloadAllowFingerprintModification;
- (id)payloadAllowPasscodeModification;
- (id)payloadAllowSimple;
- (id)payloadChangeAtNextAuth;
- (id)payloadForcePIN;
- (id)payloadManualFetchingWhenRoaming;
- (id)payloadMaxFailedAttempts;
- (id)payloadMaxGracePeriod;
- (id)payloadMaxInactivity;
- (id)payloadMaxPINAgeInDays;
- (id)payloadMinComplexChars;
- (id)payloadMinLength;
- (id)payloadMinutesUntilFailedLoginReset;
- (id)payloadPasscodeLockGracePeriod;
- (id)payloadPinHistory;
- (id)payloadRequireAlphanumeric;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
