/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMPasscodeLoginWindowDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadAdminHostInfo;
@property (nonatomic, readonly) NSArray *payloadAllowList;
@property (nonatomic, readonly) NSArray *payloadDenyList;
@property (nonatomic, readonly) NSNumber *payloadDisableConsoleAccess;
@property (nonatomic, readonly) NSNumber *payloadDisableScreenLockImmediate;
@property (nonatomic, readonly) NSNumber *payloadHideAdminUsers;
@property (nonatomic, readonly) NSNumber *payloadHideLocalUsers;
@property (nonatomic, readonly) NSNumber *payloadHideMobileAccounts;
@property (nonatomic, readonly) NSNumber *payloadIncludeNetworkUser;
@property (nonatomic, readonly) NSNumber *payloadLogOutDisabledWhileLoggedIn;
@property (nonatomic, readonly) NSString *payloadLoginwindowText;
@property (nonatomic, readonly) NSNumber *payloadPowerOffDisabledWhileLoggedIn;
@property (nonatomic, readonly) NSNumber *payloadRestartDisabled;
@property (nonatomic, readonly) NSNumber *payloadRestartDisabledWhileLoggedIn;
@property (nonatomic, readonly) NSNumber *payloadSHOWFULLNAME;
@property (nonatomic, readonly) NSNumber *payloadSHOWOTHERUSERSMANAGED;
@property (nonatomic, readonly) NSNumber *payloadShutDownDisabled;
@property (nonatomic, readonly) NSNumber *payloadShutDownDisabledWhileLoggedIn;
@property (nonatomic, readonly) NSNumber *payloadSleepDisabled;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAdminHostInfo;
- (id)payloadAllowList;
- (id)payloadDenyList;
- (id)payloadDisableConsoleAccess;
- (id)payloadDisableScreenLockImmediate;
- (id)payloadHideAdminUsers;
- (id)payloadHideLocalUsers;
- (id)payloadHideMobileAccounts;
- (id)payloadIncludeNetworkUser;
- (id)payloadLogOutDisabledWhileLoggedIn;
- (id)payloadLoginwindowText;
- (id)payloadPowerOffDisabledWhileLoggedIn;
- (id)payloadRestartDisabled;
- (id)payloadRestartDisabledWhileLoggedIn;
- (id)payloadSHOWFULLNAME;
- (id)payloadSHOWOTHERUSERSMANAGED;
- (id)payloadShutDownDisabled;
- (id)payloadShutDownDisabledWhileLoggedIn;
- (id)payloadSleepDisabled;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
