/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMRegisteredTypeResolver : NSObject

+ (Class)registeredSubClassOf:(id)arg1 withType:(id)arg2;
+ (id)registeredSubClasses;

@end
