/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSystemWebContentFilterDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAutoFilterEnabled;
@property (nonatomic, readonly) NSArray *payloadBlacklistedURLs;
@property (nonatomic, readonly) NSNumber *payloadFilterBrowsers;
@property (nonatomic, readonly) NSNumber *payloadFilterSockets;
@property (nonatomic, readonly) NSString *payloadFilterType;
@property (nonatomic, readonly) NSString *payloadOrganization;
@property (nonatomic, readonly) NSString *payloadPassword;
@property (nonatomic, readonly) NSString *payloadPayloadCertificateUUID;
@property (nonatomic, readonly) NSArray *payloadPermittedURLs;
@property (nonatomic, readonly) NSString *payloadPluginBundleID;
@property (nonatomic, readonly) NSString *payloadServerAddress;
@property (nonatomic, readonly) NSString *payloadUserDefinedName;
@property (nonatomic, readonly) NSString *payloadUserName;
@property (nonatomic, readonly) NSDictionary *payloadVendorConfig;
@property (nonatomic, readonly) NSArray *payloadWhitelistedBookmarks;
@property (readonly) Class superclass;

+ (id)WhitelistedBookmarksItem_allowedPayloadKeys;
+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAutoFilterEnabled;
- (id)payloadBlacklistedURLs;
- (id)payloadFilterBrowsers;
- (id)payloadFilterSockets;
- (id)payloadFilterType;
- (id)payloadOrganization;
- (id)payloadPassword;
- (id)payloadPayloadCertificateUUID;
- (id)payloadPermittedURLs;
- (id)payloadPluginBundleID;
- (id)payloadServerAddress;
- (id)payloadUserDefinedName;
- (id)payloadUserName;
- (id)payloadVendorConfig;
- (id)payloadWhitelistedBookmarks;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadWhitelistedBookmarksItem:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validPayloadWhitelistedBookmarksItem_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
