/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSecretCredentialsDeclaration : CEMPayloadBase {
    NSDictionary * _declarationPayload;
}

@property (readonly, retain) NSDictionary *declarationPayload;
@property (nonatomic, readonly) NSString *payloadSecret;

+ (id)allowedPayloadKeys;

- (void).cxx_destruct;
- (id)declarationPayload;
- (id)payloadSecret;
- (id)serializePayload:(id)arg1;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;

@end
