/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSystemWebDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadForceAuthenticationBeforeAutoFill;
@property (nonatomic, readonly) NSNumber *payloadForceLimitAdTracking;
@property (nonatomic, readonly) NSNumber *payloadSafariAcceptCookies;
@property (nonatomic, readonly) NSNumber *payloadSafariAllowAutoFill;
@property (nonatomic, readonly) NSNumber *payloadSafariAllowJavaScript;
@property (nonatomic, readonly) NSNumber *payloadSafariAllowPopups;
@property (nonatomic, readonly) NSNumber *payloadSafariForceFraudWarning;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadForceAuthenticationBeforeAutoFill;
- (id)payloadForceLimitAdTracking;
- (id)payloadSafariAcceptCookies;
- (id)payloadSafariAllowAutoFill;
- (id)payloadSafariAllowJavaScript;
- (id)payloadSafariAllowPopups;
- (id)payloadSafariForceFraudWarning;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
