/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSystemiCloudDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudAddressBook;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudBackup;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudBookmarks;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudCalendar;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudDesktopAndDocuments;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudDocumentSync;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudKeychainSync;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudMail;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudNotes;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudPhotoLibrary;
@property (nonatomic, readonly) NSNumber *payloadAllowCloudReminders;
@property (nonatomic, readonly) NSNumber *payloadAllowPhotoStream;
@property (nonatomic, readonly) NSNumber *payloadAllowSharedStream;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowCloudAddressBook;
- (id)payloadAllowCloudBackup;
- (id)payloadAllowCloudBookmarks;
- (id)payloadAllowCloudCalendar;
- (id)payloadAllowCloudDesktopAndDocuments;
- (id)payloadAllowCloudDocumentSync;
- (id)payloadAllowCloudKeychainSync;
- (id)payloadAllowCloudMail;
- (id)payloadAllowCloudNotes;
- (id)payloadAllowCloudPhotoLibrary;
- (id)payloadAllowCloudReminders;
- (id)payloadAllowPhotoStream;
- (id)payloadAllowSharedStream;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
