/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSecurityFDEFileVaultDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *payloadCertificateIdentifier;
@property (nonatomic, readonly) NSNumber *payloadDefer;
@property (nonatomic, readonly) NSNumber *payloadDeferDontAskAtUserLogout;
@property (nonatomic, readonly) NSNumber *payloadDeferForceAtUserLoginMaxBypassAttempts;
@property (nonatomic, readonly) NSString *payloadEnable;
@property (nonatomic, readonly) NSString *payloadOutputPath;
@property (nonatomic, readonly) NSString *payloadPassword;
@property (nonatomic, readonly) NSNumber *payloadShowRecoveryKey;
@property (nonatomic, readonly) NSNumber *payloadUseKeychain;
@property (nonatomic, readonly) NSNumber *payloadUseRecoveryKey;
@property (nonatomic, readonly) NSNumber *payloadUserEntersMissingInfo;
@property (nonatomic, readonly) NSString *payloadUsername;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadCertificateIdentifier;
- (id)payloadDefer;
- (id)payloadDeferDontAskAtUserLogout;
- (id)payloadDeferForceAtUserLoginMaxBypassAttempts;
- (id)payloadEnable;
- (id)payloadOutputPath;
- (id)payloadPassword;
- (id)payloadShowRecoveryKey;
- (id)payloadUseKeychain;
- (id)payloadUseRecoveryKey;
- (id)payloadUserEntersMissingInfo;
- (id)payloadUsername;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
