/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSystemWebContentFilterMacOSDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSArray *payloadFilterBlackList;
@property (nonatomic, readonly) NSArray *payloadFilterWhiteList;
@property (nonatomic, readonly) NSNumber *payloadRestrictWeb;
@property (nonatomic, readonly) NSArray *payloadSiteWhiteList;
@property (nonatomic, readonly) NSNumber *payloadUseContentFilter;
@property (nonatomic, readonly) NSNumber *payloadWhiteListEnabled;
@property (readonly) Class superclass;

+ (id)SiteWhiteListItem_allowedPayloadKeys;
+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadFilterBlackList;
- (id)payloadFilterWhiteList;
- (id)payloadRestrictWeb;
- (id)payloadSiteWhiteList;
- (id)payloadUseContentFilter;
- (id)payloadWhiteListEnabled;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (id)serializePayloadSiteWhiteListItem:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validPayloadSiteWhiteListItem_Dictionary:(id)arg1 parentKeyPath:(id)arg2 error:(id*)arg3;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
