/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSystemAirPrintSettingsDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowAirPrint;
@property (nonatomic, readonly) NSNumber *payloadAllowAirPrintCredentialsStorage;
@property (nonatomic, readonly) NSNumber *payloadAllowAirPrintiBeaconDiscovery;
@property (nonatomic, readonly) NSNumber *payloadForceAirPrintTrustedTLSRequirement;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowAirPrint;
- (id)payloadAllowAirPrintCredentialsStorage;
- (id)payloadAllowAirPrintiBeaconDiscovery;
- (id)payloadForceAirPrintTrustedTLSRequirement;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
