/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
 */

@interface CEMSecuritySmartCardDeclaration : CEMConfigurationBase <CEMRegisteredTypeProtocol>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSNumber *payloadAllowSmartCard;
@property (nonatomic, readonly) NSNumber *payloadCheckCertificateTrust;
@property (nonatomic, readonly) NSNumber *payloadOneCardPerUser;
@property (nonatomic, readonly) NSNumber *payloadTokenRemovalAction;
@property (nonatomic, readonly) NSNumber *payloadUserPairing;
@property (readonly) Class superclass;

+ (id)allowedPayloadKeys;
+ (id)allowedReasons;
+ (id)allowedStatusKeys;
+ (id)profileType;
+ (id)registeredClass;
+ (id)registeredType;
+ (id)restrictionPayloadKeys;

- (int)activationLevel;
- (id)assetReferences;
- (bool)multipleAllowed;
- (bool)mustBeSupervised;
- (id)payloadAllowSmartCard;
- (id)payloadCheckCertificateTrust;
- (id)payloadOneCardPerUser;
- (id)payloadTokenRemovalAction;
- (id)payloadUserPairing;
- (id)serializePayload:(id)arg1 withAssetProviders:(id)arg2;
- (bool)validPayloadDictionary:(id)arg1 error:(id*)arg2;
- (bool)validStatusDictionary:(id)arg1 error:(id*)arg2;

@end
