/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AMPCoreUI.framework/AMPCoreUI
 */

@interface AMPPrivacyViewController : UIViewController <UIViewControllerTransitioningDelegate> {
    UIButton * _continueButton;
    NSString * _identifier;
    UILabel * _infoLabel;
    OBPrivacyLinkController * _linkController;
    UIScrollView * _scrollView;
    UILabel * _titleLabel;
    NSURL * _url;
}

@property (nonatomic, retain) UIButton *continueButton;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, retain) UILabel *infoLabel;
@property (nonatomic, retain) OBPrivacyLinkController *linkController;
@property (nonatomic, retain) UIScrollView *scrollView;
@property (readonly) Class superclass;
@property (nonatomic, retain) UILabel *titleLabel;
@property (nonatomic, copy) NSURL *url;

- (void).cxx_destruct;
- (struct CGSize { double x1; double x2; })_contentSize;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)continueButton;
- (void)continueTapped:(id)arg1;
- (id)identifier;
- (id)infoLabel;
- (id)initWithIdentifier:(id)arg1 URL:(id)arg2;
- (id)linkController;
- (struct CGSize { double x1; double x2; })preferredContentSize;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (id)scrollView;
- (void)setContinueButton:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setInfoLabel:(id)arg1;
- (void)setLinkController:(id)arg1;
- (void)setScrollView:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (void)setUrl:(id)arg1;
- (id)titleLabel;
- (id)url;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
