/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDAnalyticsSubmissionCoordinator : NSObject {
    HDDaemon * _daemon;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void).cxx_destruct;
- (id)initWithDaemon:(id)arg1;
- (void)submitEvent:(id)arg1;

@end
