/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCloudSyncEndEvent : HDCloudSyncEvent <HDAnalyticSubmissionEvent> {
    NSNumber * _countSinceLastSuccess;
    double  _duration;
    NSError * _error;
    long long  _result;
    NSNumber * _timeIntervalSinceLastSuccess;
    NSError * _underlyingError;
}

@property (nonatomic, readonly, copy) NSNumber *countSinceLastSuccess;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) double duration;
@property (nonatomic, readonly, copy) NSError *error;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) long long result;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSNumber *timeIntervalSinceLastSuccess;
@property (nonatomic, readonly, copy) NSError *underlyingError;

+ (id)_underlyingErrorForError:(id)arg1;
+ (id)endEventForOperation:(long long)arg1 operationIdentifier:(id)arg2 configuration:(id)arg3 startTime:(id)arg4 result:(long long)arg5 error:(id)arg6;
+ (id)endEventForStartEvent:(id)arg1 result:(long long)arg2 error:(id)arg3;

- (void).cxx_destruct;
- (id)countSinceLastSuccess;
- (id)description;
- (double)duration;
- (id)error;
- (id)initWithProfile:(id)arg1 build:(id)arg2 internal:(bool)arg3 operation:(long long)arg4 reason:(long long)arg5 options:(unsigned long long)arg6 type:(long long)arg7 syncCirclePrefix:(id)arg8 containerID:(id)arg9 syncID:(id)arg10 operationID:(id)arg11 startTime:(id)arg12 result:(long long)arg13 error:(id)arg14;
- (long long)result;
- (id)timeIntervalSinceLastSuccess;
- (id)underlyingError;

@end
