/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCloudSyncStatusEvent : HDCloudSyncEvent <HDAnalyticSubmissionEvent> {
    NSNumber * _baseLineEpoch;
    NSNumber * _emptyZoneCount;
    NSNumber * _hasEncounteredGapInCurrentEpoch;
    NSNumber * _timeSinceDownloadSuccess;
    NSNumber * _timeSinceLastUploadForwardProgress;
    NSNumber * _timeSinceUploadSuccess;
    NSNumber * _timeUntilRebaseRequired;
}

@property (nonatomic, readonly, copy) NSNumber *baseLineEpoch;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSNumber *emptyZoneCount;
@property (nonatomic, readonly, copy) NSNumber *hasEncounteredGapInCurrentEpoch;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSNumber *timeSinceDownloadSuccess;
@property (nonatomic, readonly, copy) NSNumber *timeSinceLastUploadForwardProgress;
@property (nonatomic, readonly, copy) NSNumber *timeSinceUploadSuccess;
@property (nonatomic, readonly, copy) NSNumber *timeUntilRebaseRequired;

+ (id)_lastSuccessfulPullDateForConfiguration:(id)arg1;
+ (id)_persistedSyncStateForConfiguration:(id)arg1;
+ (id)statusEventWithConfiguration:(id)arg1;

- (void).cxx_destruct;
- (id)baseLineEpoch;
- (id)description;
- (id)emptyZoneCount;
- (id)hasEncounteredGapInCurrentEpoch;
- (id)initWithProfile:(id)arg1 build:(id)arg2 internal:(bool)arg3 operation:(long long)arg4 reason:(long long)arg5 options:(unsigned long long)arg6 type:(long long)arg7 syncCirclePrefix:(id)arg8 containerID:(id)arg9 syncID:(id)arg10 operationID:(id)arg11 syncState:(id)arg12 lastSuccessfulPullDate:(id)arg13 lastPushForwardProgressDate:(id)arg14;
- (id)timeSinceDownloadSuccess;
- (id)timeSinceLastUploadForwardProgress;
- (id)timeSinceUploadSuccess;
- (id)timeUntilRebaseRequired;

@end
