/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCloudSyncStartEvent : HDCloudSyncEvent <HDAnalyticSubmissionEvent> {
    NSNumber * _countSinceLastSuccess;
    NSNumber * _timeIntervalSinceLastSuccess;
}

@property (nonatomic, readonly, copy) NSNumber *countSinceLastSuccess;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSNumber *timeIntervalSinceLastSuccess;

+ (id)startEventForOperation:(long long)arg1 operationIdentifier:(id)arg2 configuration:(id)arg3;
+ (id)startEventWithProfile:(id)arg1 operation:(long long)arg2 operationIdentifier:(id)arg3 reason:(long long)arg4 options:(unsigned long long)arg5 syncContainerPrefix:(id)arg6 containerIdentifier:(id)arg7 syncIdentifier:(id)arg8;

- (void).cxx_destruct;
- (id)countSinceLastSuccess;
- (id)description;
- (id)initWithProfile:(id)arg1 build:(id)arg2 internal:(bool)arg3 operation:(long long)arg4 reason:(long long)arg5 options:(unsigned long long)arg6 type:(long long)arg7 syncCirclePrefix:(id)arg8 containerID:(id)arg9 syncID:(id)arg10 operationID:(id)arg11;
- (id)timeIntervalSinceLastSuccess;

@end
