/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCodableCodedQuantity : PBCodable <NSCopying> {
    HDCodableMedicalCoding * _comparatorCoding;
    HDCodableMedicalCoding * _unitCoding;
    NSString * _value;
}

@property (nonatomic, retain) HDCodableMedicalCoding *comparatorCoding;
@property (nonatomic, readonly) bool hasComparatorCoding;
@property (nonatomic, readonly) bool hasUnitCoding;
@property (nonatomic, readonly) bool hasValue;
@property (nonatomic, retain) HDCodableMedicalCoding *unitCoding;
@property (nonatomic, retain) NSString *value;

- (void).cxx_destruct;
- (id)comparatorCoding;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasComparatorCoding;
- (bool)hasUnitCoding;
- (bool)hasValue;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setComparatorCoding:(id)arg1;
- (void)setUnitCoding:(id)arg1;
- (void)setValue:(id)arg1;
- (id)unitCoding;
- (id)value;
- (void)writeTo:(id)arg1;

@end
