/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDCodableFHIRResource : PBCodable <NSCopying> {
    NSString * _accountIdentifier;
    long long  _extractionHints;
    NSString * _fhirVersion;
    NSString * _gatewayExternalID;
    struct { 
        unsigned int extractionHints : 1; 
        unsigned int receivedDate : 1; 
    }  _has;
    NSData * _rawContent;
    double  _receivedDate;
    NSString * _receivedDateTimeZoneName;
    NSString * _resourceID;
    NSString * _resourceType;
    NSString * _sourceURL;
}

@property (nonatomic, retain) NSString *accountIdentifier;
@property (nonatomic) long long extractionHints;
@property (nonatomic, retain) NSString *fhirVersion;
@property (nonatomic, retain) NSString *gatewayExternalID;
@property (nonatomic, readonly) bool hasAccountIdentifier;
@property (nonatomic) bool hasExtractionHints;
@property (nonatomic, readonly) bool hasFhirVersion;
@property (nonatomic, readonly) bool hasGatewayExternalID;
@property (nonatomic, readonly) bool hasRawContent;
@property (nonatomic) bool hasReceivedDate;
@property (nonatomic, readonly) bool hasReceivedDateTimeZoneName;
@property (nonatomic, readonly) bool hasResourceID;
@property (nonatomic, readonly) bool hasResourceType;
@property (nonatomic, readonly) bool hasSourceURL;
@property (nonatomic, retain) NSData *rawContent;
@property (nonatomic) double receivedDate;
@property (nonatomic, retain) NSString *receivedDateTimeZoneName;
@property (nonatomic, retain) NSString *resourceID;
@property (nonatomic, retain) NSString *resourceType;
@property (nonatomic, retain) NSString *sourceURL;

- (void).cxx_destruct;
- (id)accountIdentifier;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (long long)extractionHints;
- (id)fhirVersion;
- (id)gatewayExternalID;
- (bool)hasAccountIdentifier;
- (bool)hasExtractionHints;
- (bool)hasFhirVersion;
- (bool)hasGatewayExternalID;
- (bool)hasRawContent;
- (bool)hasReceivedDate;
- (bool)hasReceivedDateTimeZoneName;
- (bool)hasResourceID;
- (bool)hasResourceType;
- (bool)hasSourceURL;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (void)mergeFrom:(id)arg1;
- (id)rawContent;
- (bool)readFrom:(id)arg1;
- (double)receivedDate;
- (id)receivedDateTimeZoneName;
- (id)resourceID;
- (id)resourceType;
- (void)setAccountIdentifier:(id)arg1;
- (void)setExtractionHints:(long long)arg1;
- (void)setFhirVersion:(id)arg1;
- (void)setGatewayExternalID:(id)arg1;
- (void)setHasExtractionHints:(bool)arg1;
- (void)setHasReceivedDate:(bool)arg1;
- (void)setRawContent:(id)arg1;
- (void)setReceivedDate:(double)arg1;
- (void)setReceivedDateTimeZoneName:(id)arg1;
- (void)setResourceID:(id)arg1;
- (void)setResourceType:(id)arg1;
- (void)setSourceURL:(id)arg1;
- (id)sourceURL;
- (void)writeTo:(id)arg1;

@end
