/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDDatabaseSchemaManager : NSObject {
    NSMutableSet * _createdDatabaseNames;
    HDSQLiteDatabase * _database;
}

@property (nonatomic, retain) HDSQLiteDatabase *database;

- (void).cxx_destruct;
- (bool)_createSchemaMigrationTableIfNeededForDatabaseName:(id)arg1 error:(id*)arg2;
- (id)_schemaTableNameForDatabaseName:(id)arg1;
- (long long)currentVersionForSchema:(id)arg1 databaseName:(id)arg2 error:(id*)arg3;
- (id)database;
- (id)initWithDatabase:(id)arg1;
- (void)setDatabase:(id)arg1;
- (bool)setVersion:(long long)arg1 schema:(id)arg2 databaseName:(id)arg3 error:(id*)arg4;

@end
