/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDFHIRCredentialEntity : HDHealthEntity

+ (id)columnsDefinition;
+ (id)databaseTable;
+ (long long)protectionClass;

@end
