/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRAVDistantOutputDevice : MRAVOutputDevice <NSSecureCoding> {
    NSDictionary * _modelSpecificInfo;
    _MRAVOutputDeviceDescriptorProtobuf * _protobuf;
    MRAVOutputDeviceSourceInfo * _sourceInfo;
}

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)MACAddress;
- (float)batteryLevel;
- (bool)canAccessRemoteAssets;
- (bool)canRelayCommunicationChannel;
- (id)descriptor;
- (unsigned int)deviceSubtype;
- (unsigned int)deviceType;
- (void)encodeWithCoder:(id)arg1;
- (id)groupID;
- (bool)hasBatteryLevel;
- (id)initWithCoder:(id)arg1;
- (id)initWithDescriptor:(id)arg1;
- (bool)isDeviceGroupable;
- (bool)isGroupLeader;
- (bool)isGroupable;
- (bool)isLocalDevice;
- (bool)isRemoteControllable;
- (id)logicalDeviceID;
- (id)modelID;
- (id)modelSpecificInfo;
- (id)name;
- (bool)requiresAuthorization;
- (id)sourceInfo;
- (bool)supportsExternalScreen;
- (id)uid;

@end
