/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRAVDistantEndpoint : MRAVEndpoint <NSSecureCoding> {
    NSObject<OS_dispatch_queue> * _accessSerialQueue;
    MRDistantExternalDevice * _distantExternalDevice;
    MRAVDistantOutputDevice * _distantGroupLeader;
    NSArray * _distantOutputDevices;
    NSXPCListenerEndpoint * _externalDeviceListenerEndpoint;
    NSString * _instanceIdentifier;
    bool  _isLocalEndpoint;
    NSString * _localizedName;
    bool  _proxyGroupPlayer;
    NSString * _uniqueIdentifier;
}

@property (nonatomic, retain) MRAVDistantOutputDevice *distantGroupLeader;
@property (nonatomic, copy) NSArray *distantOutputDevices;
@property (nonatomic, retain) NSXPCListenerEndpoint *externalDeviceListenerEndpoint;
@property (nonatomic, copy) NSString *localizedName;
@property (getter=isProxyGroupPlayer, nonatomic) bool proxyGroupPlayer;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)designatedGroupLeader;
- (id)distantGroupLeader;
- (id)distantOutputDevices;
- (void)encodeWithCoder:(id)arg1;
- (id)externalDevice;
- (id)externalDeviceListenerEndpoint;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithDescriptor:(id)arg1;
- (id)instanceIdentifier;
- (bool)isEqual:(id)arg1;
- (bool)isLocalEndpoint;
- (bool)isProxyGroupPlayer;
- (id)localizedName;
- (id)outputDevices;
- (void)setDistantGroupLeader:(id)arg1;
- (void)setDistantOutputDevices:(id)arg1;
- (void)setExternalDeviceListenerEndpoint:(id)arg1;
- (void)setLocalizedName:(id)arg1;
- (void)setProxyGroupPlayer:(bool)arg1;
- (id)uniqueIdentifier;

@end
