/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRExternalDevice : NSObject {
    unsigned int  _connectionState;
    struct { 
        unsigned int type; 
        bool isProxyGroupPlayer; 
        unsigned int reserved[2]; 
    }  _systemMusicContextInfo;
    bool  _valid;
}

@property (nonatomic, readonly) unsigned int connectionState;
@property (nonatomic, readonly) _MROriginProtobuf *customOrigin;
@property (nonatomic, readonly) _MRDeviceInfoMessageProtobuf *deviceInfo;
@property (nonatomic, readonly) NSString *hostName;
@property (nonatomic, readonly) NSString *name;
@property (getter=isPaired, nonatomic, readonly) bool paired;
@property (nonatomic, readonly) long long port;
@property (nonatomic, readonly) MRSupportedProtocolMessages *supportedMessages;
@property (nonatomic, readonly) struct { unsigned int x1; bool x2; unsigned int x3[2]; } systemMusicContextInfo;
@property (getter=isUsingSystemPairing, nonatomic) bool usingSystemPairing;
@property (getter=isValid, nonatomic, readonly) bool valid;
@property (nonatomic) bool wantsNowPlayingArtworkNotifications;
@property (nonatomic) bool wantsNowPlayingNotifications;
@property (nonatomic) bool wantsVolumeNotifications;

- (id)_init;
- (void)connectWithOptions:(unsigned int)arg1;
- (unsigned int)connectionState;
- (id)currentClientUpdatesConfigMessage;
- (id)customOrigin;
- (id)deviceInfo;
- (void)disconnect:(id)arg1;
- (id)errorForCurrentState;
- (id)hostName;
- (bool)isPaired;
- (bool)isUsingSystemPairing;
- (bool)isValid;
- (void)modifyOutputContextOfType:(unsigned int)arg1 addingDeviceUIDs:(id)arg2 removingDeviceUIDs:(id)arg3 settingDeviceUIDs:(id)arg4 withReplyQueue:(id)arg5 completion:(id /* block */)arg6;
- (id)name;
- (void)outputDeviceVolume:(id)arg1 queue:(id)arg2 completion:(id /* block */)arg3;
- (void)ping:(double)arg1 callback:(id /* block */)arg2 withQueue:(id)arg3;
- (long long)port;
- (void)sendClientUpdatesConfigMessage;
- (void)sendCustomData:(id)arg1 withName:(id)arg2;
- (void)setConnectionStateCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setCustomDataCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setNameCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setOutputContextCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setOutputDeviceVolume:(float)arg1 outputDevice:(id)arg2 queue:(id)arg3 completion:(id /* block */)arg4;
- (void)setPairingAllowedCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setPairingCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setSupportedMessages:(id)arg1;
- (void)setUsingSystemPairing:(bool)arg1;
- (void)setVolume:(float)arg1 queue:(id)arg2 completion:(id /* block */)arg3;
- (void)setVolumeCallback:(id /* block */)arg1 withQueue:(id)arg2;
- (void)setWantsNowPlayingArtworkNotifications:(bool)arg1;
- (void)setWantsNowPlayingNotifications:(bool)arg1;
- (void)setWantsVolumeNotifications:(bool)arg1;
- (id)supportedMessages;
- (struct { unsigned int x1; bool x2; unsigned int x3[2]; })systemMusicContextInfo;
- (void)unpair;
- (void)volumeWithQueue:(id)arg1 completion:(id /* block */)arg2;
- (bool)wantsNowPlayingArtworkNotifications;
- (bool)wantsNowPlayingNotifications;
- (bool)wantsVolumeNotifications;

@end
