/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKAccountOwnerType : HKMedicalType

+ (id)accountOwnerType;

- (Class)dataObjectClass;

@end
