/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKAllergyRecordType : HKMedicalType

+ (id)allergyRecordType;

- (Class)dataObjectClass;

@end
