/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKConditionRecordType : HKMedicalType

+ (id)conditionRecordType;

- (Class)dataObjectClass;

@end
