/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKConditionRecord : HKMedicalRecord <HDCoding, NSCopying, NSSecureCoding> {
    HKInspectableValue * _abatement;
    NSString * _asserter;
    NSArray * _bodySitesCodings;
    NSArray * _categoryCodings;
    HKMedicalCoding * _clinicalStatusCoding;
    NSArray * _conditionCodings;
    HKInspectableValue * _onset;
    HKMedicalDate * _recordedDate;
    NSArray * _severityCodings;
    HKMedicalCoding * _verificationStatusCoding;
}

@property (nonatomic, readonly, copy) HKInspectableValue *abatement;
@property (nonatomic, readonly, copy) NSString *asserter;
@property (nonatomic, readonly, copy) NSArray *bodySitesCodings;
@property (nonatomic, readonly, copy) NSArray *categoryCodings;
@property (nonatomic, readonly, copy) HKMedicalCoding *clinicalStatusCoding;
@property (nonatomic, readonly, copy) NSArray *conditionCodings;
@property (nonatomic, readonly) HKConditionRecordType *conditionRecordType;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) HKInspectableValue *onset;
@property (nonatomic, readonly, copy) HKMedicalDate *recordedDate;
@property (nonatomic, readonly, copy) NSArray *severityCodings;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) HKMedicalCoding *verificationStatusCoding;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)bodySitesCodingsPreferredSystems;
+ (id)categoryCodingsPreferredSystems;
+ (id)clinicalStatusCodingPreferredSystems;
+ (id)conditionCodingsPreferredSystems;
+ (id)conditionRecordWithNote:(id)arg1 enteredInError:(bool)arg2 modifiedDate:(id)arg3 FHIRIdentifier:(id)arg4 extractionVersion:(long long)arg5 device:(id)arg6 metadata:(id)arg7 conditionCodings:(id)arg8 categoryCodings:(id)arg9 asserter:(id)arg10 abatement:(id)arg11 onset:(id)arg12 recordedDate:(id)arg13 clinicalStatusCoding:(id)arg14 verificationStatusCoding:(id)arg15 severityCodings:(id)arg16 bodySitesCodings:(id)arg17;
+ (id)defaultDisplayString;
+ (id)severityCodingsPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;
+ (id)verificationStatusCodingPreferredSystems;

- (void).cxx_destruct;
- (id)_init;
- (void)_setAbatement:(id)arg1;
- (void)_setAsserter:(id)arg1;
- (void)_setBodySitesCodings:(id)arg1;
- (void)_setCategoryCodings:(id)arg1;
- (void)_setClinicalStatusCoding:(id)arg1;
- (void)_setConditionCodings:(id)arg1;
- (void)_setOnset:(id)arg1;
- (void)_setRecordedDate:(id)arg1;
- (void)_setSeverityCodings:(id)arg1;
- (void)_setVerificationStatusCoding:(id)arg1;
- (id)_validateConfiguration;
- (id)abatement;
- (id)asserter;
- (id)bodySitesCodings;
- (id)bodySitesCodingsTasks;
- (id)categoryCodings;
- (id)categoryCodingsTasks;
- (id)clinicalStatusCoding;
- (id)clinicalStatusCodingTasks;
- (id)conditionCodings;
- (id)conditionCodingsTasks;
- (id)conditionRecordType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (id)onset;
- (id)recordedDate;
- (id)severityCodings;
- (id)severityCodingsTasks;
- (id)verificationStatusCoding;
- (id)verificationStatusCodingTasks;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
