/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKDiagnosticTestResultType : HKMedicalType

+ (id)diagnosticTestResultType;

- (Class)dataObjectClass;

@end
