/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicationDispenseRecordType : HKMedicalType

+ (id)medicationDispenseRecordType;

- (Class)dataObjectClass;

@end
