/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicationRecord : HKMedicalRecord <HDCoding, NSCopying, NSSecureCoding> {
    NSString * _asserter;
    HKMedicalDate * _assertionDate;
    long long  _assertionType;
    NSArray * _dosages;
    HKMedicalDate * _earliestDosageDate;
    HKMedicalDate * _effectiveEndDate;
    HKMedicalDate * _effectiveStartDate;
    NSArray * _medicationCodings;
    bool  _notTaken;
    NSArray * _reasonForUseCodings;
    NSArray * _reasonsNotTakenCodings;
    HKMedicalCoding * _statusCoding;
}

@property (nonatomic, readonly, copy) NSString *asserter;
@property (nonatomic, readonly, copy) HKMedicalDate *assertionDate;
@property (nonatomic, readonly) long long assertionType;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSArray *dosages;
@property (nonatomic, readonly, copy) HKMedicalDate *earliestDosageDate;
@property (nonatomic, readonly, copy) HKMedicalDate *effectiveEndDate;
@property (nonatomic, readonly, copy) HKMedicalDate *effectiveStartDate;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSArray *medicationCodings;
@property (nonatomic, readonly) HKMedicationRecordType *medicationRecordType;
@property (nonatomic, readonly) bool notTaken;
@property (nonatomic, readonly, copy) NSArray *reasonForUseCodings;
@property (nonatomic, readonly, copy) NSArray *reasonsNotTakenCodings;
@property (nonatomic, readonly, copy) HKMedicalCoding *statusCoding;
@property (readonly) Class superclass;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)defaultDisplayString;
+ (id)medicationCodingsPreferredSystems;
+ (id)medicationRecordWithNote:(id)arg1 enteredInError:(bool)arg2 modifiedDate:(id)arg3 FHIRIdentifier:(id)arg4 extractionVersion:(long long)arg5 device:(id)arg6 metadata:(id)arg7 medicationCodings:(id)arg8 assertionType:(long long)arg9 asserter:(id)arg10 assertionDate:(id)arg11 statusCoding:(id)arg12 dosages:(id)arg13 earliestDosageDate:(id)arg14 reasonForUseCodings:(id)arg15 notTaken:(bool)arg16 reasonsNotTakenCodings:(id)arg17 effectiveStartDate:(id)arg18 effectiveEndDate:(id)arg19;
+ (id)reasonForUseCodingsPreferredSystems;
+ (id)reasonsNotTakenCodingsPreferredSystems;
+ (id)statusCodingPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_init;
- (void)_setAsserter:(id)arg1;
- (void)_setAssertionDate:(id)arg1;
- (void)_setAssertionType:(long long)arg1;
- (void)_setDosages:(id)arg1;
- (void)_setEarliestDosageDate:(id)arg1;
- (void)_setEffectiveEndDate:(id)arg1;
- (void)_setEffectiveStartDate:(id)arg1;
- (void)_setMedicationCodings:(id)arg1;
- (void)_setNotTaken:(bool)arg1;
- (void)_setReasonForUseCodings:(id)arg1;
- (void)_setReasonsNotTakenCodings:(id)arg1;
- (void)_setStatusCoding:(id)arg1;
- (id)_validateConfiguration;
- (id)asserter;
- (id)assertionDate;
- (long long)assertionType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dosages;
- (id)earliestDosageDate;
- (id)effectiveEndDate;
- (id)effectiveStartDate;
- (void)encodeWithCoder:(id)arg1;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (id)medicationCodings;
- (id)medicationCodingsTasks;
- (id)medicationRecordType;
- (bool)notTaken;
- (id)reasonForUseCodings;
- (id)reasonForUseCodingsTasks;
- (id)reasonsNotTakenCodings;
- (id)reasonsNotTakenCodingsTasks;
- (id)statusCoding;
- (id)statusCodingTasks;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
