/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicationDispenseRecord : HKMedicalRecord <HDCoding, NSCopying, NSSecureCoding> {
    HKCodedQuantity * _daysSupplyQuantity;
    NSArray * _dosages;
    HKMedicalDate * _earliestDosageDate;
    HKMedicalDate * _handOverDate;
    NSArray * _medicationCodings;
    HKMedicalDate * _preparationDate;
    HKCodedQuantity * _quantityDispensed;
    HKMedicalCoding * _statusCoding;
}

@property (nonatomic, readonly, copy) HKCodedQuantity *daysSupplyQuantity;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSArray *dosages;
@property (nonatomic, readonly, copy) HKMedicalDate *earliestDosageDate;
@property (nonatomic, readonly, copy) HKMedicalDate *handOverDate;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSArray *medicationCodings;
@property (nonatomic, readonly) HKMedicationDispenseRecordType *medicationDispenseRecordType;
@property (nonatomic, readonly, copy) HKMedicalDate *preparationDate;
@property (nonatomic, readonly, copy) HKCodedQuantity *quantityDispensed;
@property (nonatomic, readonly, copy) HKMedicalCoding *statusCoding;
@property (readonly) Class superclass;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)defaultDisplayString;
+ (id)medicationCodingsPreferredSystems;
+ (id)medicationDispenseRecordWithNote:(id)arg1 enteredInError:(bool)arg2 modifiedDate:(id)arg3 FHIRIdentifier:(id)arg4 extractionVersion:(long long)arg5 device:(id)arg6 metadata:(id)arg7 medicationCodings:(id)arg8 quantityDispensed:(id)arg9 preparationDate:(id)arg10 handOverDate:(id)arg11 dosages:(id)arg12 earliestDosageDate:(id)arg13 statusCoding:(id)arg14 daysSupplyQuantity:(id)arg15;
+ (id)statusCodingPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_init;
- (void)_setDaysSupplyQuantity:(id)arg1;
- (void)_setDosages:(id)arg1;
- (void)_setEarliestDosageDate:(id)arg1;
- (void)_setHandOverDate:(id)arg1;
- (void)_setMedicationCodings:(id)arg1;
- (void)_setPreparationDate:(id)arg1;
- (void)_setQuantityDispensed:(id)arg1;
- (void)_setStatusCoding:(id)arg1;
- (id)_validateConfiguration;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)daysSupplyQuantity;
- (id)description;
- (id)dosages;
- (id)earliestDosageDate;
- (void)encodeWithCoder:(id)arg1;
- (id)handOverDate;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (id)medicationCodings;
- (id)medicationCodingsTasks;
- (id)medicationDispenseRecordType;
- (id)preparationDate;
- (id)quantityDispensed;
- (id)statusCoding;
- (id)statusCodingTasks;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
