/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicationOrderType : HKMedicalType

+ (id)medicationOrderType;

- (Class)dataObjectClass;

@end
