/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicationRecordType : HKMedicalType

+ (id)medicationRecordType;

- (Class)dataObjectClass;

@end
