/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKProcedureRecordType : HKMedicalType

+ (id)procedureRecordType;

- (Class)dataObjectClass;

@end
