/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKProcedureRecord : HKMedicalRecord <HDCoding, NSCopying, NSSecureCoding> {
    NSArray * _bodySitesCodings;
    NSArray * _categoryCodings;
    NSArray * _complicationsCodings;
    HKMedicalDate * _executionEndDate;
    HKMedicalDate * _executionStartDate;
    NSArray * _followUpsCodings;
    bool  _notPerformed;
    NSArray * _outcomeCodings;
    NSArray * _performers;
    NSArray * _procedureCodings;
    NSArray * _reasonCodings;
    NSArray * _reasonsNotPerformedCodings;
    HKMedicalCoding * _statusCoding;
}

@property (nonatomic, readonly, copy) NSArray *bodySitesCodings;
@property (nonatomic, readonly, copy) NSArray *categoryCodings;
@property (nonatomic, readonly, copy) NSArray *complicationsCodings;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) HKMedicalDate *executionEndDate;
@property (nonatomic, readonly, copy) HKMedicalDate *executionStartDate;
@property (nonatomic, readonly, copy) NSArray *followUpsCodings;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool notPerformed;
@property (nonatomic, readonly, copy) NSArray *outcomeCodings;
@property (nonatomic, readonly, copy) NSArray *performers;
@property (nonatomic, readonly, copy) NSArray *procedureCodings;
@property (nonatomic, readonly) HKProcedureRecordType *procedureRecordType;
@property (nonatomic, readonly, copy) NSArray *reasonCodings;
@property (nonatomic, readonly, copy) NSArray *reasonsNotPerformedCodings;
@property (nonatomic, readonly, copy) HKMedicalCoding *statusCoding;
@property (readonly) Class superclass;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)bodySitesCodingsPreferredSystems;
+ (id)categoryCodingsPreferredSystems;
+ (id)complicationsCodingsPreferredSystems;
+ (id)defaultDisplayString;
+ (id)followUpsCodingsPreferredSystems;
+ (id)outcomeCodingsPreferredSystems;
+ (id)procedureCodingsPreferredSystems;
+ (id)procedureRecordWithNote:(id)arg1 enteredInError:(bool)arg2 modifiedDate:(id)arg3 FHIRIdentifier:(id)arg4 extractionVersion:(long long)arg5 device:(id)arg6 metadata:(id)arg7 procedureCodings:(id)arg8 performers:(id)arg9 executionStartDate:(id)arg10 executionEndDate:(id)arg11 notPerformed:(bool)arg12 statusCoding:(id)arg13 categoryCodings:(id)arg14 reasonCodings:(id)arg15 reasonsNotPerformedCodings:(id)arg16 outcomeCodings:(id)arg17 complicationsCodings:(id)arg18 followUpsCodings:(id)arg19 bodySitesCodings:(id)arg20;
+ (id)reasonCodingsPreferredSystems;
+ (id)reasonsNotPerformedCodingsPreferredSystems;
+ (id)statusCodingPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_init;
- (void)_setBodySitesCodings:(id)arg1;
- (void)_setCategoryCodings:(id)arg1;
- (void)_setComplicationsCodings:(id)arg1;
- (void)_setExecutionEndDate:(id)arg1;
- (void)_setExecutionStartDate:(id)arg1;
- (void)_setFollowUpsCodings:(id)arg1;
- (void)_setNotPerformed:(bool)arg1;
- (void)_setOutcomeCodings:(id)arg1;
- (void)_setPerformers:(id)arg1;
- (void)_setProcedureCodings:(id)arg1;
- (void)_setReasonCodings:(id)arg1;
- (void)_setReasonsNotPerformedCodings:(id)arg1;
- (void)_setStatusCoding:(id)arg1;
- (id)_validateConfiguration;
- (id)bodySitesCodings;
- (id)bodySitesCodingsTasks;
- (id)categoryCodings;
- (id)categoryCodingsTasks;
- (id)complicationsCodings;
- (id)complicationsCodingsTasks;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)executionEndDate;
- (id)executionStartDate;
- (id)followUpsCodings;
- (id)followUpsCodingsTasks;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (bool)notPerformed;
- (id)outcomeCodings;
- (id)outcomeCodingsTasks;
- (id)performers;
- (id)procedureCodings;
- (id)procedureCodingsTasks;
- (id)procedureRecordType;
- (id)reasonCodings;
- (id)reasonCodingsTasks;
- (id)reasonsNotPerformedCodings;
- (id)reasonsNotPerformedCodingsTasks;
- (id)statusCoding;
- (id)statusCodingTasks;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
