/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKUnknownRecordType : HKMedicalType

+ (id)unknownRecordType;

- (Class)dataObjectClass;

@end
