/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKVaccinationRecordType : HKMedicalType

+ (id)vaccinationRecordType;

- (Class)dataObjectClass;

@end
