/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface _ATXIntentUtils : NSObject

+ (id)firstIntent:(id)arg1 inAppLaunchSession:(id)arg2;
+ (id)getActivityTypeFromNSUAType:(id)arg1;
+ (id)getBundleIdAndIntentTypeFromIntentKey:(id)arg1;
+ (id)getBundleIdFromIntentKey:(id)arg1;
+ (id)getBundleIdsFromIntentKeys:(id)arg1;
+ (id)getIntentKeyForBundleId:(id)arg1 intentType:(id)arg2;
+ (id)getIntentTypeFromIntentKey:(id)arg1;
+ (id)getIntentTypesFromIntentKeys:(id)arg1;
+ (id)getNSUATypefromActivityType:(id)arg1;
+ (id /* block */)intentKeyFilterForCandidateBundleIds:(id)arg1 candidateIntentTypes:(id)arg2;
+ (bool)isIntentKey:(id)arg1;
+ (bool)isNSUAType:(id)arg1;
+ (void)prefillIntentHistograms;

@end
