/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface _ATXNSUALogger : NSObject

+ (void)logDonatedNSUAs;

@end
