/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXIntentPredictionTypes : NSObject

+ (id)engagementTypeToString:(unsigned long long)arg1;
+ (id)feedbackSourceToString:(unsigned long long)arg1;

@end
