/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXIntent : NSObject <NSSecureCoding> {
    NSString * _bundleId;
    id  _intent;
    unsigned long long  _intentType;
}

@property (nonatomic, readonly) NSString *bundleId;
@property (nonatomic, readonly) id intent;
@property (nonatomic, readonly) unsigned long long intentType;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)bundleId;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithIntent:(id)arg1 bundleId:(id)arg2 type:(unsigned long long)arg3;
- (id)intent;
- (unsigned long long)intentType;
- (bool)isEqual:(id)arg1;

@end
