/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXIntentPredictionServer : NSObject <ATXIntentPredictionInterface, NSXPCListenerDelegate> {
    bool  _checkEntitlements;
    NSXPCListener * _listener;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSXPCListenerEndpoint *endpoint;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)dealloc;
- (id)endpoint;
- (void)getIntentPredictionsForCandidateBundleIdentifiers:(id)arg1 candidateIntentTypes:(id)arg2 intentUILimit:(int)arg3 reply:(id /* block */)arg4;
- (id)init;
- (id)initAnonymousListener;
- (id)initWithListener:(id)arg1;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)sendFeedbackWithResponse:(id)arg1;

@end
