/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXSlotIntentResolver : NSObject

+ (id)getIntentForSlot:(id)arg1 intentType:(id)arg2;
+ (id)getSlotForIntentType:(id)arg1 andContext:(id)arg2;
+ (bool)isRequiredForIntent:(id)arg1;

- (id)init;

@end
