/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiometricSupport.framework/BiometricSupport
 */

@interface BiometricKitEventLogger : NSObject {
    unsigned int  _eventList;
    int  _eventListLength;
    bool  _operationCreated;
    NSObject<OS_dispatch_queue> * _queue;
    bool  _terminalFlushPending;
    NSObject<OS_dispatch_source> * _timer;
}

+ (id)logger;

- (void).cxx_destruct;
- (void)appendEventValue:(unsigned int)arg1;
- (void)flushEvents;
- (id)init;
- (void)logEventOrCode:(unsigned long long)arg1;

@end
