/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AdPlatformsInternal.framework/AdPlatformsInternal
 */

@interface ADAttributionService : ADSingleton <ADAttribution_XPC, NSXPCListenerDelegate> {
    NSString * _bundleID;
    NSXPCListener * _listener;
}

@property (nonatomic, retain) NSString *bundleID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (retain) NSXPCListener *listener;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (int)appRunState;
- (void)attachDownloadDataTo:(id)arg1 forAdamID:(id)arg2;
- (void)attachSearchMetadataTo:(id)arg1 forAdamID:(id)arg2;
- (id)bundleID;
- (id)init;
- (id)listener;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)makeAttributionRequestWithObject:(id)arg1 andHandler:(id /* block */)arg2;
- (void)overrideAttributionData:(id)arg1;
- (bool)productionClient;
- (void)requestAttributionDetails:(id /* block */)arg1;
- (void)requestAttributionDetailsWithBlock:(id /* block */)arg1;
- (void)setBundleID:(id)arg1;
- (void)setListener:(id)arg1;

@end
