/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LAEventConfigurationViewController : LASettingsViewController {
    id  _eventConfiguration;
    NSString * _eventEmitterName;
    NSString * _eventName;
    UIBarButtonItem * _saveBarButtonItem;
}

@end
