/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LAEventSettingsController : LASettingsViewController {
    NSSet * _configurableListenerNames;
    NSMutableArray * _currentAssignments;
    LAListenerTableViewDataSource * _dataSource;
    NSString * _eventName;
    ActivatorEventViewHeader * _headerView;
    UIView * _headerWrapper;
    NSDictionary * _incompatibleListenerNames;
    NSArray * _modes;
    bool  _modesContainsLockScreen;
    NSArray * _pendingCompatibleModes;
    bool  _pendingIsMutuallyCompatible;
    NSString * _pendingListenerName;
    UISearchBar * _searchBar;
    UISearchController * _searchController;
    bool  _viaSpecifier;
}

@end
