/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LAEvent : NSObject <NSCoding> {
    bool  _handled;
    NSString * _mode;
    NSString * _name;
    NSDictionary * _userInfo;
}

@property (getter=isHandled, nonatomic) bool handled;
@property (nonatomic, readonly) NSString *mode;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, copy) NSDictionary *userInfo;

+ (id)eventWithName:(id)arg1;
+ (id)eventWithName:(id)arg1 mode:(id)arg2;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 mode:(id)arg2;
- (bool)isHandled;
- (id)mode;
- (id)name;
- (void)setHandled:(bool)arg1;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
