/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LAListenerConfigurationViewController : LASettingsViewController {
    id  _listenerConfiguration;
    NSString * _listenerEmitterName;
    NSString * _listenerName;
    UIBarButtonItem * _saveBarButtonItem;
}

@end
