/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LAModeSettingsController : LASettingsViewController {
    UIBarButtonItem * _editItem;
    NSString * _eventMode;
    NSMutableDictionary * _events;
    NSArray * _groups;
    NSArray * _resolvedModes;
    UISearchController * _searchController;
    NSString * _searchText;
}

@end
