/* Generated by RuntimeBrowser
   Image: /Library/TweakInject/Activator.dylib
 */

@interface LASettingsViewController : UIViewController {
    <LASettingsViewControllerDelegate> * _delegate;
    UINavigationController * _savedNavigationController;
    UITableView * _tableView;
}

+ (void)initialize;

@end
