/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSContext : CLSObject <CLSRelationable> {
    long long  __authorizationStatus;
    NSString * __contentStoreIdentifier;
    NSString * __currentActivityID;
    long long  __displayOrder;
    NSString * __title;
    NSString * __topic;
    NSURL * __universalLinkURL;
    bool  _active;
    NSString * _identifier;
    NSArray * _path;
    NSString * _storeIdentifier;
    NSString * _storeTeamID;
    long long  _type;
}

@property (nonatomic) long long _authorizationStatus;
@property (nonatomic, copy) NSString *_contentStoreIdentifier;
@property (nonatomic, copy) NSString *_currentActivityID;
@property (nonatomic) long long _displayOrder;
@property (nonatomic, retain) NSArray *_path;
@property (nonatomic, copy) NSString *_title;
@property (nonatomic, copy) NSString *_topic;
@property (nonatomic, retain) NSURL *_universalLinkURL;
@property (getter=isActive, nonatomic) bool active;
@property (nonatomic) long long authorizationStatus;
@property (nonatomic, copy) NSString *contentStoreIdentifier;
@property (nonatomic, readonly) CLSActivity *currentActivity;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long displayOrder;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, readonly) NSArray *path;
@property (nonatomic, copy) NSString *storeIdentifier;
@property (nonatomic, copy) NSString *storeTeamID;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSString *topic;
@property (nonatomic) long long type;
@property (nonatomic, retain) NSURL *universalLinkURL;

+ (id)allowedTopics;
+ (id)arrayOfStringClasses;
+ (bool)conformsToProtocol:(id)arg1;
+ (id)objectIDPathFromIdentifierPath:(id)arg1;
+ (id)relations;
+ (id)reservedContextTypes;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (long long)_authorizationStatus;
- (id)_contentStoreIdentifier;
- (id)_currentActivityID;
- (long long)_displayOrder;
- (id)_init;
- (id)_path;
- (id)_title;
- (id)_topic;
- (id)_universalLinkURL;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
- (void)addChildContext:(id)arg1;
- (long long)authorizationStatus;
- (void)becomeActive;
- (id)childContextWithIdentifier:(id)arg1;
- (bool)conformsToProtocol:(id)arg1;
- (id)contentStoreIdentifier;
- (id)createNewActivity;
- (id)currentActivity;
- (void)descendantMatchingIdentifierPath:(id)arg1 completion:(id /* block */)arg2;
- (id)description;
- (id)dictionaryRepresentation;
- (long long)displayOrder;
- (long long)effectiveAuthorizationStatus;
- (void)encodeWithCoder:(id)arg1;
- (id)identifier;
- (id)initWithCoder:(id)arg1;
- (id)initWithInternalType:(long long)arg1 identifier:(id)arg2 title:(id)arg3;
- (id)initWithType:(long long)arg1 identifier:(id)arg2 title:(id)arg3;
- (bool)isActive;
- (void)mergeWithObject:(id)arg1;
- (id)newItemProvider;
- (id)path;
- (void)removeFromParent;
- (void)resignActive;
- (void)setActive:(bool)arg1;
- (void)setAuthorizationStatus:(long long)arg1;
- (void)setContentStoreIdentifier:(id)arg1;
- (void)setDisplayOrder:(long long)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setPathAndGenerateObjectID:(id)arg1;
- (void)setStoreIdentifier:(id)arg1;
- (void)setStoreTeamID:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setTopic:(id)arg1;
- (void)setType:(long long)arg1;
- (void)setUniversalLinkURL:(id)arg1;
- (void)set_authorizationStatus:(long long)arg1;
- (void)set_contentStoreIdentifier:(id)arg1;
- (void)set_currentActivityID:(id)arg1;
- (void)set_displayOrder:(long long)arg1;
- (void)set_path:(id)arg1;
- (void)set_title:(id)arg1;
- (void)set_topic:(id)arg1;
- (void)set_universalLinkURL:(id)arg1;
- (id)storeIdentifier;
- (id)storeTeamID;
- (id)title;
- (id)topic;
- (long long)type;
- (id)universalLinkURL;
- (bool)validateObject:(id*)arg1;

@end
