/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSEndpointConnection : NSObject <CLSClientDelegate> {
    bool  _connectionBorked;
    NSXPCListenerEndpoint * _endpoint;
    bool  _interrupted;
    NSRecursiveLock * _lock;
    id /* block */  _onConnect;
    id /* block */  _onInterupt;
    NSString * _overrideBundleIdentifier;
    int  _progressdAvailableToken;
    NSXPCConnection * _serverConnection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id /* block */ onConnect;
@property (nonatomic, copy) id /* block */ onInterupt;
@property (nonatomic, retain) NSString *overrideBundleIdentifier;
@property (readonly) Class superclass;

+ (id)classKitEnvironment;
+ (id)instanceForEndpoint:(id)arg1;
+ (bool)isAllowedToMakeXPCCalls;
+ (bool)isClassKitEnabled;
+ (bool)isInDevelopmentEnvironment;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_envokeOnInteruptCallback;
- (void)_registerForDarwinNotifications;
- (void)_updateBundleIdentifier:(id)arg1 forConnection:(id)arg2 completion:(id /* block */)arg3;
- (void)accountChanged;
- (void)addBarrierBlock:(id /* block */)arg1;
- (void)client:(id)arg1 recievedNewDevMode:(int)arg2;
- (void)connect;
- (void)connectionBorked;
- (void)connectionInterupted;
- (id)dataServer:(id /* block */)arg1;
- (void)dealloc;
- (void)deleteAppWithBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (id)init;
- (id)initWithEndpoint:(id)arg1;
- (void)invalidate;
- (bool)isBorked;
- (void)listAppsWithCompletion:(id /* block */)arg1;
- (id /* block */)onConnect;
- (id /* block */)onInterupt;
- (id)overrideBundleIdentifier;
- (id)server:(id /* block */)arg1;
- (id)serverConnection;
- (void)setOnConnect:(id /* block */)arg1;
- (void)setOnInterupt:(id /* block */)arg1;
- (void)setOverrideBundleIdentifier:(id)arg1;
- (void)setOverrideBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (id)syncDataServer:(id /* block */)arg1;
- (id)syncServer:(id /* block */)arg1;
- (id)syncUtilityServer:(id /* block */)arg1;
- (id)utilityServer:(id /* block */)arg1;

@end
