/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSMetaProperty : CLSObject {
    <CLSMetaPropertyValue> * __value;
    NSString * _name;
}

@property (nonatomic, retain) <CLSMetaPropertyValue> *_value;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, retain) <CLSMetaPropertyValue> *value;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_value;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 value:(id)arg2;
- (id)name;
- (void)setValue:(id)arg1;
- (void)set_value:(id)arg1;
- (id)value;

@end
