/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSQuantityItem : CLSActivityItem {
    double  __quantity;
}

@property (nonatomic) double _quantity;
@property (nonatomic) double quantity;

+ (bool)supportsSecureCoding;

- (id)_init;
- (double)_quantity;
- (id)description;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithIdentifier:(id)arg1 title:(id)arg2;
- (double)quantity;
- (void)setQuantity:(double)arg1;
- (void)set_quantity:(double)arg1;

@end
