/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UISegmentedControlDividerImage : UIImage

+ (bool)supportsSecureCoding;

- (bool)_suppressesAccessibilityHairlineThickening;

@end
