/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEODataXPCSessionTaskQueuePendingTask : NSObject {
    double  _expiresAtTime;
    bool  _processed;
    GEODataXPCSessionTask<GEODataXPCSessionTaskQueueTask> * _task;
}

@property (nonatomic, readonly) double expiresAtTime;
@property (nonatomic, readonly) bool processed;
@property (nonatomic, retain) GEODataXPCSessionTask<GEODataXPCSessionTaskQueueTask> *task;

+ (id)pendingTask:(id)arg1;

- (void).cxx_destruct;
- (double)expiresAtTime;
- (void)processResultOnce:(int)arg1 xpcReply:(id)arg2 error:(id)arg3;
- (bool)processed;
- (void)setTask:(id)arg1;
- (id)task;

@end
