/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOToolRequester : NSObject <GEOToolProxy> {
    <GEOToolProxy> * _proxy;
}

+ (id)sharedRequester;
+ (void)useLocalProxy;
+ (void)useProxy:(Class)arg1;
+ (void)useRemoteProxy;

- (void).cxx_destruct;
- (unsigned long long)calculatePurgableSpaceForUrgency:(int)arg1;
- (unsigned long long)freePurgableSpace:(unsigned long long)arg1 forUrgency:(int)arg2;
- (id)getDefault:(id)arg1;
- (id)init;
- (void)lockDBs;
- (void)resetMapDataExtension;
- (void)unlockDBs;
- (void)validateMapLayerDataWithHandler:(id /* block */)arg1;

@end
